### ISSUE TITLE
External subtitle support

### ISSUE THREAD

**Issue by DIYgod** [MoePlayer/DPlayer#100]
- ~~`srt` format~~ WebVTT
- under the danmaku

**Comment by DIYgod** [comment]
References: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/track
 https://www.html5rocks.com/zh/tutorials/track/basics/

**Comment by donnes** [comment]
Currently HTMl5 video does not support `.src` files and `.vtt` instead. I think we'll need to use a third-party library like http://www.storiesinflight.com/js_videosub to make it possible

**Comment by DIYgod** [comment]
WebVTT is easiest and it should be top priority, the other formats maybe need a second thought.

**Comment by DIYgod** [comment]
Done. https://github.com/MoePlayer/DPlayer/commit/9c09d324a758fa2d32fe5492007eb06db74a07f5

Further:
Switching show and hide button

**Comment by DIYgod** [comment]
Subtitle button and events: c145ecfe90eed8a43201079fcefed4c478b3bf08
