### ISSUE TITLE
m3u8视频在safari中无法播放

### ISSUE THREAD

**Issue by cqsn558** [MoePlayer/DPlayer#1007]
m3u8地址：https://ae01.alicdn.com/kf/H6112015087ee4d28a21b393f727c6ca3C.jpg
测试地址：https://jsbin.com/pekejiqoyi/1/edit?html,output
       测试地址在Windows系统测试正常，在macOS系统的safari测试提示“视频加载失败”，视频的总时间可以正常显示出来，不能播放视频，测试机macOS版本为10.15.6

**Comment by LiJiaPeng001** [comment]
?解决了么
