### ISSUE TITLE
Tencet cloud mp4 video can not play on mobile phones （腾讯云的mp4视频没法在手机上播放）

### ISSUE THREAD

**Issue by jhxxs** [MoePlayer/DPlayer#1023]
Mp4 Video from Tencent Cloud can't be played on ios or android mobile phones, which works fine on PC.
I tried to open the video url on mobile browsers, such as safari, mp4 file can't be played directly on phones.
What module should I import to support mp4 video file ?
Tence Video url here: **[link](http://1302618392.vod2.myqcloud.com/2ba88585vodcq1302618392/89f67fe85285890806924511019/iNtsbiFuGDkA.mp4)**

腾讯云的mp4视频没法在手机上播放，电脑浏览器正常播放，我试过在手机上打开视频连接，没法播放。
所以我需要引入什么解码库吗？
腾讯云视频链接：**[测试视频](http://1302618392.vod2.myqcloud.com/2ba88585vodcq1302618392/89f67fe85285890806924511019/iNtsbiFuGDkA.mp4)**

**Comment by 1265578519** [comment]
https://jsbin.com/radumasavu/edit?html,output
你用的什么浏览器？我这可以播放呀

**Comment by jhxxs** [comment]
> https://jsbin.com/radumasavu/edit?html,output
> 你用的什么浏览器？我这可以播放呀

测试视频没法在手机浏览器上播放，我用videojs试过后发现，应该是手机上不能播放这个格式的MP4视频，电脑上可以，然后转码以后也可以在手机上播放了。
看样子应该不是dplayer的问题，而是手机解码不兼容。因为我在手机上直接打开视频链接也不能播放，必须用第三方播放器才可以。

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/92366063-3dbc7180-f127-11ea-8da8-e4ce8276901f.jpg)

嗯，应该是你的手机问题。。我这手机都是正常播放的
