### ISSUE TITLE
My redmi 4x phone can't show bilibili url video

### ISSUE THREAD

**Issue by zytx121** [MoePlayer/DPlayer#107]
I use your demo to test,but also show loading fail.
![image](https://user-images.githubusercontent.com/10410257/28600859-5a8f8d8c-71e7-11e7-8202-cfef90e50812.png)
![image](https://user-images.githubusercontent.com/10410257/28600862-5ec37c10-71e7-11e7-916f-f50410043846.png)

**Only for  bilibili  url, other urls  show rightly.** And i test  chrome，Firefox.  nobody  works!! XD

**Comment by zytx121** [comment]
and i switch to  video  label  ,  when  use  bilibili  url it doesn't work in my phone  either.

**Comment by DIYgod** [comment]
Bilibili video parse is not supported further.
