### ISSUE TITLE
flvplayer don't support config param

### ISSUE THREAD

**Issue by zhj135** [MoePlayer/DPlayer#117]
dplayer use flv.js to create player, like:
    ## const flvPlayer = flvjs.createPlayer({
        type: 'flv',
        url: this.option.video.url
    });
however, flv.js have the second param, like:
    ## function createPlayer(mediaDataSource: MediaDataSource, config?: Config): Player

it seems I can't use the second param: config.what should I do to solve this problem?

thanks for your dplayer, it helps me a lot

**Comment by DIYgod** [comment]
Version `1.7.0` support initing FLV outside, see [#flv-support](http://dplayer.js.org/#flv-support)
