### ISSUE TITLE
if i want to add svg icon , how should i do ? 

### ISSUE THREAD

**Issue by daviscai** [MoePlayer/DPlayer#120]
if i want to add svg icon , how should i do ? 

```
/**
* SVG used by DPlayer
*/

const svgSource = {
    'play': ['0 0 16 32', 'M15.552 15.168q0.448 0.32 0.448 0.832 0 0.448-0.448 0.768l-13.696 8.512q-0.768 0.512-1.312 0.192t-0.544-1.28v-16.448q0-0.96 0.544-1.28t1.312 0.192z']
};
```

how create the play svg icon data?

**Comment by RexSkz** [comment]
The items in `svgSource` have the same format: `'type': ['viewbox', 'path']`. `type` is a custom name, you can get `viewbox` and `path` in your specific `.svg` file.

You can only use svg which has only one `<path>`. SVG editor software generated files usually have more elements, it's a pity that you can't use them.
