### ISSUE TITLE
can not full screen!!

### ISSUE THREAD

**Issue by satakwwl** [MoePlayer/DPlayer#121]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
Get out

**Comment by satakwwl** [comment]
garbage

**Comment by dixyes** [comment]
@satakwwl 考你个英语阅读理解

If you want to report a bug, please provide the following information:

The steps to reproduce.
A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
Which versions of DPlayer, and which browser / OS are affected by this issue?

阅读以上文字并且回答
1.为什么过气网红很生气
2.为什么issue得不到解答

**Comment by RexSkz** [comment]
undirectlookable /_\
