### ISSUE TITLE
不能全屏播放

### ISSUE THREAD

**Issue by sickneet** [MoePlayer/DPlayer#123]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by hnsylitao** [comment]
提供下demo 还有重现方式

**Comment by sickneet** [comment]
发送自 Windows 10 版邮件应用

发件人: hnsylitao
发送时间: 2017年8月26日 14:43
收件人: MoePlayer/DPlayer
抄送: sickneet; Author
主题: Re: [MoePlayer/DPlayer] 不能全屏播放 (#123)

提供下demo 还有重现方式
