### ISSUE TITLE
切换视频的时候，弹幕无法显示

### ISSUE THREAD

**Issue by lg1987** [MoePlayer/DPlayer#128]
需要一个视频列表功能，
网页载入以后，点击播放，然后切换视频，可以正常加载弹幕。
网页载入以后，直接点列表中的其他视频，就无法加载弹幕了。包括您的演示文档，点击Switch Video也是如此。
使用的api是`switchVideo`

**Comment by DIYgod** [comment]
I can not reproduce it.
Please provide more information.

**Comment by msterzhang** [comment]
我也遇见这个问题了，其实弹幕是加载了的，只不过就是不能给动画让弹幕移动,弹幕位于最左端。如图：
![image](https://user-images.githubusercontent.com/31364579/67212970-c4a12680-f44f-11e9-98c8-f2a2cf8da14d.png)

**Comment by msterzhang** [comment]
已经查到原因，就是切换视频后，点击播放的时候，这个类名没有变化，按理说点击播放后这个类名应该改变，才能显示弹幕。望作者修复Bug，方便的话告知我如何修改！感谢感谢
![image](https://user-images.githubusercontent.com/31364579/67215268-c66ce900-f453-11e9-8555-ecae86923a36.png)
