### ISSUE TITLE
谷歌浏览器全屏无响应

### ISSUE THREAD

**Issue by sunkejava** [MoePlayer/DPlayer#129]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by dixyes** [comment]
为了更快得到帮助 建议你按照模板提示反馈

1.复现步骤
2.dplayer与操作系统 浏览器的版本
3.如果可能的话用jsfiddle或codepen提供一个demo
