### ISSUE TITLE
DPlayer播放器画质清晰度

### ISSUE THREAD

**Issue by nba4488** [MoePlayer/DPlayer#130]
你好，DPlayer播放器里面的画质清晰度这个功能缺陷问题情况，要是可以这个画质清晰度，就算是很完美了

**Comment by fghrsh** [comment]
？？？ 清晰度不是看 视频源 的吗？

**Comment by fghrsh** [comment]
![tFzvn.png](http://fp1.fghrsh.net/2017/09/01/tFzvn.png)
你要的 清晰度切换 已经实现啦 (〜￣△￣)〜：[DPlayer 清晰度切换 Demo](https://devtest.fghrsh.net/2017-09-01/)

**Comment by mrltr** [comment]
> ![tFzvn.png](https://camo.githubusercontent.com/9044db3fc9e16ed8302185621ba3aca63cf89203/687474703a2f2f6670312e6667687273682e6e65742f323031372f30392f30312f74467a766e2e706e67)
> 你要的分辨率切换已经实现啦（〜￣△￣）〜：[DPlayer逐步切换Demo](https://devtest.fghrsh.net/2017-09-01/)

你的demo链接已经失效了，请问是怎么实现的呢
