### ISSUE TITLE
switchVideo不支持hls切换

### ISSUE THREAD

**Issue by guoyawei** [MoePlayer/DPlayer#131]
dp.switchVideo({
                    url:hls,
                    type:'hls'
  });

 dp.switchVideo({
                    url:mp4,
                });
                dp.play();

切换mp4 正常,  

场景是  直播下面会有回看或者点播,,希望可以实现互切.  切回hls 无法播放   
希望支持 tx

**Comment by guoyawei** [comment]
现在的做法是 每次重新实例化一下 播放器做切换

**Comment by guoyawei** [comment]
手机版体验不太好 因为 播放按钮在移动端就特别小  点的时候经常会跟进度条冲突   希望增加播放按钮控制  可以控制屏幕中间出现播放按钮

**Comment by guoyawei** [comment]
还有啊    直播页面不友好了   直播应该不显示进度条 and 时间戳

**Comment by DIYgod** [comment]
Done. https://github.com/MoePlayer/DPlayer/commit/38c10cbd5a49eb652fa3db10461e0983a1485ef0

**Comment by hukuiabc** [comment]
hi guoyawei
你的需求和我是一样的，我现在几个都是HLS流，一切换就播不了，切换不了，但是我看这个bug已经关闭了。请问你的解决了么？
