### ISSUE TITLE
DPlayer播放器视频画质清晰度增加功能使用就很完美了

### ISSUE THREAD

**Issue by nba4488** [MoePlayer/DPlayer#136]
你好，我有事情想要咨询你，可是为什么网上解析视频接口不能够视频画质清晰度切换，为什么网上解析视频接口没有像这样切换视频画质清晰使用的功能，DPlayer播放器还是有缺陷漏洞问题情况，要是可以解决这个缺陷漏洞问题情况功能使用就很完美了，要是视频画质清晰度可以增加很稳定确定正确1080P和原画还有4K这样就更好了，
![image](https://user-images.githubusercontent.com/29298373/30162719-8159c1e2-9408-11e7-88dc-778743b3c797.png)

**Comment by hnsylitao** [comment]
dplayer 只是视频播放器
至于你说的视频清晰切换功能已经有了
清晰度是不同源而已
当你只有一个视频源的时候是不能支持清晰度的

**Comment by DIYgod** [comment]
@hnsylitao Blocked
