### ISSUE TITLE
跨域请求别人的服务器的资源的问题-- 跨域请求别人的服务器的资源的问题 Cross domain requests for resources from other servers

### ISSUE THREAD

**Issue by cosmosjack** [MoePlayer/DPlayer#137]
中文
目的：请求一个网络上其他服务器的m3u8文件并能够播放
现状：m3u8文件和视频切片在本地服务器就没有问题,请求其他人的就会出现《XMLHttpRequest cannot load http://zy.512wx.com/20170909/Q0HjEHQQ/1500kb/hls/ppvod6058000.ts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://haiyang.net' is therefore not allowed access.》这种问题。导致无法播放
调式：找到《hls.min.js》文件中http请求,但是不知道怎么修改,自己用ajax模拟跨域请求可以返回二进制数据但我不知道怎么处理（ajax方法里只有json、XML、文本处理）如果返回的不是json数据正常是不会走success 里边的。然后看了complete方法好像也没有处理http请求后返回的内容。
想到的解决方案：在（XDomainRequest ，XMLHttpRequest）中添加如 ajax 中JSONP请求的思路,然后可以在DPlayer对象中设置 URL 是否是跨域的资源。
最后：我本身是不懂JS的还望看到问题觉得简单的不要笑我，我在网上查找到的解决方法很多都是不合适的（他们那种的环境是：自己是服务器,然后别人请求我们时出现了 Access-Control-Allow-Orign）。所以我希望如果这个问题已经被解决了，还望大家跟我说下怎么用的，在各地方解决的。
         谢谢--叫我 飘 英文 jack

ENGLISH
Purpose: request a m3u8 file on another server on the network and play it
Status: m3u8 files and video sections there is no problem in the local server, ask other people there will be "XMLHttpRequest cannot load http://zy.512wx.com/20170909/Q0HjEHQQ/1500kb/hls/ppvod6058000.ts. No'Access-Control-Allow-Origin'header is present on the requested resource. Origin'http://haiyang.net' is therefore not allowed access." this problem. Can not play
Mode: find "http hls.min.js" request file, but do not know how to modify their use of Ajax simulation of cross domain requests can return binary data but I don't know how to deal with (Ajax, XML, JSON method only text processing) if the return is not normal JSON data will not go inside the success. Then I looked at the complete method, as if I didn't handle the content returned after the HTTP request.
The solution that you think: in XDomainRequest (XMLHttpRequest), add the idea of the JSONP request in Ajax, and then you can set whether the URL is a cross domain resource in the DPlayer object.
Finally: I don't know JS itself is also hope to see the problem that simple solutions do not laugh at me, I find online are not appropriate (what kind of environment is: the emergence of Access-Control-Allow-Orign is their own server, and then asked us). So I hope that if this problem has been solved, I hope you will tell me how to use it and solve it in different places.
Thank you - call me piao English jack

**Comment by kslr** [comment]
third party server ?

**Comment by dixyes** [comment]
参考 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS

**Comment by Copay** [comment]
@cosmosjack 逾越cors需要目标服务器的支持

**Comment by hnsylitao** [comment]
can do proxy

**Comment by DIYgod** [comment]
You shouldn't request others' file.
