### ISSUE TITLE
dplayer的全屏回调事件怎么写。为什么我用了就报错了。是不是用错了

### ISSUE THREAD

**Issue by jinsom** [MoePlayer/DPlayer#138]
Video events里面使用没有问题
Player events用就报错：Uncaught TypeError: Cannot read property 'push' of undefined
写法：
dp.on("fullscreen", function(){
//do something
});

**Comment by DIYgod** [comment]
Update DPlayer to latest version (1.9.1+)

**Comment by jinsom** [comment]
thanks
