### ISSUE TITLE
一个正常的mp4地址为什么播放了，本地用video标签却没有问题。

### ISSUE THREAD

**Issue by jinsom** [MoePlayer/DPlayer#139]
报错：Uncaught (in promise) DOMException: The element has no supported sources.
视频地址：http://gxmov.a.yximgs.com/udata/W_NmKv5r7ifms_zh.mp4
<video src="http://gxmov.a.yximgs.com/udata/W_NmKv5r7ifms_zh.mp4" controls="controls"></video>

**Comment by jinsom** [comment]
没人啊

**Comment by kslr** [comment]
please check the code.

**Comment by jinsom** [comment]
可是代码是没有问题的，因为换一个地址就可以，比如这个地址是没有问题的。
https://lightsns.oss-cn-qingdao.aliyuncs.com/demo_video.mp4

**Comment by jinsom** [comment]
我刚刚又排查了一下，把这个视频下载到自己服务器 再引用是没有问题的。
让我不解的是：为什么用自带的video标签可以引用，而用dplayer却直接报错。

**Comment by RexSkz** [comment]
你的视频在我这里没问题，请贴一下相关代码，或者提供一个可以复现该 bug 的、尽可能小的 demo。
