### ISSUE TITLE
全屏按钮点击没有效果Flash Player 26.0.0.151

### ISSUE THREAD

**Issue by Bubbleinpit** [MoePlayer/DPlayer#140]
在Chrome和Edge都没有用

**Comment by Copay** [comment]
@Bubbleinpit dplayer并不基于flash哦，建议贴出具体的错误信息

**Comment by Bubbleinpit** [comment]
抱歉我只是一个用户，我在这个网站看视频http://www.qiqipu.com，发现不能全屏，然后右键播放界面找到一个反馈按钮来的这里。所以我不是一个使用本播放器的开发者，给不了太具体的错误信息。只能说我现在用的win10专业版1703，chrome和edge上测试都不能全屏，我的显示器分辨率是2560*1080.
