### ISSUE TITLE
无法全屏

### ISSUE THREAD

**Issue by Bubbleinpit** [MoePlayer/DPlayer#141]
### 问题的发现：
视频链接：http://www.qiqipu.com/dsj/omj/35656/player.html?35656-0-0
**点击全屏按钮没有任何效果**
### 问题出现的环境：
- Dplayer版本：我无法判断，网站和播放器中都没有找到相关信息，点进上述链接即可查看播放器
- 操作系统：Windows 10 Pro 1703 64位
- 浏览器：Chrome v60.0.3112.113 64位 / Edge v40.15063.0.0
- 显示器分辨率：2560*1080

**Comment by DIYgod** [comment]
It caused by this website rather than DPlayer, I'm not the website administrator, so I can not help you.
