### ISSUE TITLE
How to use subtitle features? And what about I am using a md

### ISSUE THREAD

**Issue by xiaotan828** [MoePlayer/DPlayer#160]
seem that var doesn't work directly in md document

**Comment by DIYgod** [comment]
I think [document](http://dplayer.js.org/docs/#/?id=options) is clear, what is your problem?

**Comment by xiaotan828** [comment]
I've read that, but "var"doesn't work in markdown document

**Comment by xiaotan828** [comment]
It's a wonderful player and I really want to make subtitle feature work

**Comment by xiaotan828** [comment]
Sorry, my bad, I've solved it, thanks!
