### ISSUE TITLE
So You leave a QQ Group number in README and refuse people join in?

### ISSUE THREAD

**Issue by gonejack** [MoePlayer/DPlayer#164]

**Comment by DIYgod** [comment]
@gonejack Sorry about that, but I noly refuse stupid people who can't even answer a simple verification question.

**Comment by gonejack** [comment]
![0f90179a-c5bb-418f-b42c-2b655da8efcc](https://user-images.githubusercontent.com/2720676/33802472-08a2155c-ddb3-11e7-8dbf-03d4810931bd.png)
Where is the verification question if you think it's important.

**Comment by DIYgod** [comment]
It caused by QQ for Mac, maybe you should have a talk with Tencent.

**Comment by NathanZhengNaixian** [comment]
V2ex 观光团。。。

**Comment by huangshuwei** [comment]
V2exer 到此一游

**Comment by lizhichao** [comment]
😁

**Comment by canxden** [comment]
LOL

**Comment by corningsun** [comment]
哈哈，一到github就飙英语～～

**Comment by kirigayakazushin** [comment]
v2exer Strong onlookers

**Comment by jerry12547** [comment]
到此一游，围观大佬

**Comment by liwanglin12** [comment]
Please do not sign in the issue. 
@DIYgod Lock Conversation plz.
