### ISSUE TITLE
mp4 no sound

### ISSUE THREAD

**Issue by xiaotan828** [MoePlayer/DPlayer#165]
https://blog.txshore.tech/2017/12/10/GoT-s07e03/#more
the video doesn't have sound, but it has sound when playing locally, so it's no the video itsself's problem, anyone can help!

**Comment by DIYgod** [comment]
Your video is blocked by CORS policy, I can't play it.

**Comment by xiaotan828** [comment]
I've solved the sound problem, that is because the sound format was not AAC
But now I meet problem while adding subtitles in MD document.

While I write {% ****** "subtitle=url.vtt" %} in MD document, the whole player doesn't work, I don't know how to add subtitle code in {% %}

**Comment by DIYgod** [comment]
See: https://github.com/MoePlayer/hexo-tag-dplayer#usage
