### ISSUE TITLE
Suggestion: horizontal screen mode on mobile?

### ISSUE THREAD

**Issue by lemos1235** [MoePlayer/DPlayer#173]
It's not good to watch a video on vertical screen in mobile phone. How about adding a horizontal screen mode on it?

**Comment by kn007** [comment]
你好，不好意思，英文一般。中文跟你聊一下。
这个受限于手机，我之前跟作者探讨过和实验过。
现在没有合适的api可以实现。目前W3C草案还未实行，只有部分Android支持。
https://www.w3.org/TR/screen-orientation

这个会持续跟进，当然办法也不是没有，那就是使用手机内置播放器功能，但这ui就随手机了。这要看作者了，我个人意见是等草案实施。

如果你有发现任何其他同类js播放器可以支持，请告知。或者你也可以直接PR，谢谢。
