### ISSUE TITLE
it looks like you spell 'destroy' into 'distory'

### ISSUE THREAD

**Issue by newming** [MoePlayer/DPlayer#178]
https://github.com/MoePlayer/DPlayer/blob/52607916a45c2b8d3a27cb4f55eefa5dc769a529/src/time.js#L91

**Comment by DIYgod** [comment]
@newming 妈耶

**Comment by kn007** [comment]
wow，bug

**Comment by newming** [comment]
在观摩大神代码 :blush:

**Comment by DIYgod** [comment]
Fixed. https://github.com/MoePlayer/DPlayer/commit/1331b6d5c02ac11b076d210386370eaf9af23ade
