### ISSUE TITLE
Full screen doesn't work

### ISSUE THREAD

**Issue by enjoybeta** [MoePlayer/DPlayer#180]
In short, I was viewing on dilidili, a video provider using this as one of its online video player. But the full screen button doesn't work anyhow.

The example link I am testing on: http://www.dilidili.wang/watch3/56102/
Need to attention the "线路3" is the button to use DPlayer as online video

Windows 10 Version 10.0.16299 Build 16299
Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by kn007** [comment]
兄弟，不是，这个问题，你不应该跟dilidili反馈么？
站上DPlayer用着1.5.1的版本，现在都1.17.4了。
不受理过旧版本问题，谢谢。

**Comment by enjoybeta** [comment]
这样啊，我给他们发个邮件吧
