### ISSUE TITLE
hls requests didn't encode special uri characters

### ISSUE THREAD

**Issue by awatuna** [MoePlayer/DPlayer#187]
The hls m3u8 generated by nginx-vod-module does not uri encode special characters (space to %20..etc)

videojs handles this fine, but not dplayer unde firefox.

This could be fixed by encodeURIComponent hls requests.

`http://abc.com/2017 01 01.mp4/seg-1-v1-a1.ts -> http://abc.com/2017%2001%2001.mp4/seg-1-v1-a1.ts`

**Comment by DIYgod** [comment]
It might be caused by [hls.js](https://github.com/video-dev/hls.js), I recommend creating an issue to hls.js repo.
