### ISSUE TITLE
when subtitles enabled, causes the video to cross the domain without playing

### ISSUE THREAD

**Issue by oyjcmyn** [MoePlayer/DPlayer#189]
The same video URL, when subtitles enabled, causes the video to cross the domain without playing.
Subtitles are in the same domain name.

![qq](https://user-images.githubusercontent.com/24839942/35256312-37234eda-002e-11e8-9e7a-2e3f129e81c9.png)

**Comment by DIYgod** [comment]
The video must support cross-domain if screenshot or subtitle enabled.

**Comment by oyjcmyn** [comment]
同样的视频地址（不支持跨域的视频），在flowplayer.js 播放放器和wordpress自带的视频播放器都是能正常播放。所以也希望dplayer也能正常播放
