### ISSUE TITLE
最新版本的谷歌浏览器不能全屏观看

### ISSUE THREAD

**Issue by zengzizeng** [MoePlayer/DPlayer#192]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
Chrome 64.0.3282.119 with Windows 10:
* Fullscreen&Web page full screen test:
  * DPlayer: Test pass.
  * DPlayer Lite: Test pass.

**Comment by kn007** [comment]
结果：未能复现。LZ环境信息不明、未提供。
建议：请禁用所有插件后，清空缓存，在隐身模式测试一下。
