### ISSUE TITLE
关于播放器声道的问题

### ISSUE THREAD

**Issue by SongChao1123** [MoePlayer/DPlayer#201]
电脑开播音频流采样率跟手机端一样，都是44100Hz和双声道
目前测试如下：
电脑开播，H5播放音频正常，客户端app播放音频正常
手机开播 H5播放音频不正常，客户端app播放音频正常
手机历史视频 H5播放音频不正常，客户端app播放音频正常

请问下作者，目前不正常的情况会有杂音和双重音，DPlayer能设置声道吗？

**Comment by DIYgod** [comment]
应该视频流的问题，请到相应上游仓库反馈：

[hls.js](https://github.com/video-dev/hls.js) [flv.js](https://github.com/Bilibili/flv.js)
