### ISSUE TITLE
On the demo page Quality switching

### ISSUE THREAD

**Issue by puzzle9** [MoePlayer/DPlayer#205]
v 1.22.0

http://dplayer.js.org/#quality-switching

![2018-02-12 15-13-13](https://user-images.githubusercontent.com/13518196/36086880-d2357700-1009-11e8-9fbc-f40b35d060f1.png)

**Comment by DIYgod** [comment]
Fixed. https://github.com/MoePlayer/DPlayer/commit/360878bcc7df3570914f810e9dc4dd5b4616213b
