### ISSUE TITLE
Hide video duration bar on live stream

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [MoePlayer/DPlayer#206]
I'm writing an electron application to watch television live stream for myself, using DPlayer 1.12.0.
And I'm noticed duration bar is shown even on live stream.
![2018-02-18 18-45-10](https://user-images.githubusercontent.com/36147447/36350926-ea276068-14db-11e8-870b-954cf69d80cc.png)
I think when player is playing live stream, duration bar and seeking video manually will be disabled.
Sorry for my bad English.

---

我正在給自己寫一個可以收看電視直播的Electron程式，其中播放器部分使用了DPlayer 1.12.0。
在測試的時候發現播放的視頻進度條即使是在播放直播流的時候仍舊會顯示。
個人認爲播放器的視頻進度條和時間調整的功能應該得在播放直播流的時候禁用，以免出現各種問題，像香港電台的電視直播頁面，視頻控件沒有視頻進度條顯示。

**Comment by DIYgod** [comment]
http://dplayer.js.org/#live

**Comment by WUGqnwvMQPzl** [comment]
@DIYgod 剛才試了一下，視頻進度條確實隱藏了，但還是可以使用快捷鍵手動調整播放時間，是否考慮修復？

**Comment by MasterShu** [comment]
@DIYgod http://dplayer.js.org/#live 
This URL is not fount!
