### ISSUE TITLE
can not play on safari！

### ISSUE THREAD

**Issue by teacup1105** [MoePlayer/DPlayer#207]
a web use your dplayer for all the videos to play online, suddenly oneday I can't play any videos on this website by using my macbook, it can just only play with my iPhone , how is this work?

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by dixyes** [comment]
so you need provide the name or url of that site and your browser version or we cannot do anything for you
你需要提供这个网站的名字或者网址以及你的浏览器版本（以及系统信息等等） 否则并没法愉快的修复问题
