### ISSUE TITLE
最近版本画质切换URL有问题

### ISSUE THREAD

**Issue by mcm4869** [MoePlayer/DPlayer#208]
例如站点地址为：
https://example.com

视频地址为：
https://a.com/720p.mp4

但是按照demo设置画质切换后地址为：
https://example.com/[%22https://a.com/720p.mp4%22]

1.16的版本测试没有此问题，麻烦看下什么原因，谢谢

**Comment by mcm4869** [comment]
1.21.3版本测试正常

**Comment by DIYgod** [comment]
Fixed. 94f8dea8312b52b9c7c51e58d48f3a4f51390b89
