### ISSUE TITLE
Context menu item "Video info" has a problem on Firefox

### ISSUE THREAD

**Issue by journey-ad** [MoePlayer/DPlayer#210]
>env:
Windows 10
Firefox 58.0.2 x64
DPlayer v1.22.2 (current version of dplayer.js.org)

Right click on the player, click context menu item "Video info", Firefox will open a new tab.
The reason should be HTML a tag attribute `target="_blank"`.

Chinese:
右键点击播放器，点击菜单项“视频信息”，Firefox会打开一个新标签页。
应该是a标签属性`target="_blank"`的锅。

**Comment by DIYgod** [comment]
Fixed. c3dc1047353361e912a7132575ee3a3ee8f212f9
