### ISSUE TITLE
hello，请问下关于DPlayer点击全屏后禁止竖版的问题

### ISSUE THREAD

**Issue by SongChao1123** [MoePlayer/DPlayer#224]
hello 我又来了，我是忠实用户啊，老是给你提问题，不太好意思了。哈哈
问题是： DPlayer播放器中我手机IOS点击了全屏后，我想禁用竖版的操作，我只想要播放器全屏后横版。
PS：我查询了相关的资料 http://www.php.cn/html5-tutorial-384976.html
发现我们能支持 x5-video-orientation="landscape" 这个参数吗？

**Comment by kn007** [comment]
谢谢支持，但你高兴太早了。
首先，这个帖子介绍的并不是原生html5。
其次例子使用到是系统原生播放器。

我之前也犯了一样的错误。

**Comment by kn007** [comment]
如果你仔细搜索就知道了。。
我当时是越搜索脸越红。。。

**Comment by SongChao1123** [comment]
@kn007 大佬始终领先我们一步。 
但是我搜索后发现IOS中点击DPlayer播放器的全屏后，是IOS原生的了，网页端并不能控制他禁止竖版。

**Comment by 1265578519** [comment]
我大D站的播放器，听说支持WebTorrent，来试试

**Comment by Dennisky** [comment]
为什么我点全屏都没反应呢？
