### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by FirstAurora183** [MoePlayer/DPlayer#228]
1. 直接在vue单页面项目中使用DPlayer，能获取到视频但是点了之后一直转圈
2. Github下载的Dplayer的demo好像跑不起来
3. vue-dplayer的readme的文档链接好像挂了 
我后来用的vue-dplayer跑起来的视频，不明白为什么直接使用DPlayer不行 _(:зゝ∠)_

**Comment by kn007** [comment]
第一个问题：看浏览器console和network怎么说。
第二个问题：github的demo的source禁止外链，也就是说，你下载本地后测试，会被认为是盗链。
第三个问题：vue-dplayer的readme的文档链接，不应该问vue-dplayer吗？直接用DPlayer不行，你不给个链接，我听到你这么说，我也很难过，但无能为力。

**Comment by DIYgod** [comment]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

`demo` folder is used for development, run `npm run dev` then open `localhost:8080`

**Comment by FirstAurora183** [comment]
Sorry, my description is not detailed.Wait me to tidy it up, I will submit a new issue
