### ISSUE TITLE
Question about the Barrage data.弹幕数据问题

### ISSUE THREAD

**Issue by Noahsarker** [MoePlayer/DPlayer#229]
我使用Dplayer的弹幕有些问题，浏览器的无痕模式播放视频并发送弹幕即可重现。每次新开无痕窗口，都获取不到弹幕数据。

I have some problems with Dplayer's barrage data, It can be reproduced when I use chrome incognito mode.Every time a new incognito window is opened, I can't receive the barrage I sent through the last incognito window.

我从[官方备份数据](https://raw.githubusercontent.com/MoePlayer/DPlayer-data/master/dans.json)中拉出两组数据和我得到的数据来做下对比。

I got two groups of data frome https://raw.githubusercontent.com/MoePlayer/DPlayer-data/master/dans.json and compared with the data I got my own.
```
{"_id":{"$oid":"59c149be555a0215ba1b169f"},"author":"DIYgod","time":0,"text":"1","color":"#fff","type":"right","ip":"183.152.92.225","referer":"http://127.0.0.1/demo/","player":["9E2E3368B56CDBB46"],"__v":0}
{"_id":{"$oid":"59c149c2555a0215ba1b16a0"},"author":"DIYgod","time":0,"text":"1","color":"#fff","type":"right","ip":"183.152.92.225","referer":"http://127.0.0.1/demo/","player":["9E2E3368B56CDBB46"],"__v":0}
```
另一组数据
the othre one 
```
{"_id":{"$oid":"59c1bfda555a0215ba1b16a8"},"author":"rylon","time":459.967676,"text":"llll","color":"#fff","type":"right","ip":"183.160.44.197","referer":"http://x.movcms.com/apps/vod/?id=o0024vhexlj\u0026type=qq","player":["DPlayerSBSUBDanmuwm21"],"__v":0}
{"_id":{"$oid":"59c1bfee555a0215ba1b16a9"},"author":"rylon","time":421.808136,"text":"ddddd","color":"#fff","type":"right","ip":"183.160.44.197","referer":"http://x.movcms.com/apps/vod/?id=o0024vhexlj\u0026type=qq","player":["DPlayerSBSUBDanmuwm21"],"__v":0}
{"_id":{"$oid":"59c1c03e555a0215ba1b16aa"},"author":"rylon","time":33.312351,"text":"asdfasdfasdf","color":"#fff","type":"right","ip":"183.160.44.197","referer":"http://x.movcms.com/apps/vod/?id=o0024vhexlj\u0026type=qq","player":["DPlayerSBSUBDanmuwm21"],"__v":0}
```
这是我自己分别在两次无痕模式下发送的弹幕数据

this is what I got 
```
{"_id":{"$oid":"5aaa0ae7c07f5f000faad709"},"author":"DIYgod","time":7.671622,"text":"测试弹幕","color":"#fff","type":"right","ip":"::ffff:183.226.56.82","player":["b242a2d1ddef83dc461fb19f2d72684c"],"__v":0}
{"_id":{"$oid":"5aaa0d1ec07f5f000faad70a"},"author":"DIYgod","time":15.329281,"text":"为什么不行呢","color":"#fff","type":"right","ip":"::ffff:183.226.56.82","player":["6be3ba35cad7bd3fffcff665c872c430"],"__v":0}
```

可以看到官方备份的数据中，对同一视频的player字段内容是固定的，而我开了两次无痕得到的数据中，player字段是不同的，除此之外还少了referer字段的数据，我门外汉看不懂源码，不知道后端是依靠什么来精准推送弹幕数据的，我也不能判断是否为dplayer的问题，特此咨询。

The difference is the data of  'player' and 'referer',I have no referer data and my two player data is different. I don’t know what's wrong with it .

**Comment by Noahsarker** [comment]
英语渣 尽力了。。

**Comment by DIYgod** [comment]
- returned data from API is different with backup data

- `player` in API data is the same as `option.danmaku.id`, you should make sure every player has unique danmaku id,  different danmaku id result in different data.
