### ISSUE TITLE
A  problem in vue spa,click start have circles around problems

### ISSUE THREAD

**Issue by XavierShi** [MoePlayer/DPlayer#231]
在vue项目中，使用DPlayer点击开始一直转圈的问题。   
In vue project, using DPlayer click start have circles around problems.  
mac 10.13.3  
node 9.8.0
vue 2.5.2  
dplayer  1.22.2  

.vue 文件代码  
The vue file code  
```vue
<template>
  <div class="d-player">
    DPlayer Demo
    <div id="dplayer"></div>
    <!--<vue-dplayer :options="options">-->
    <!--</vue-dplayer>-->
  </div>
</template>

<script type="text/ecmascript-6">
  import DPlayer from 'dplayer'
  // import VueDplayer from 'vue-dplayer'

  export default {
    mounted() {
      const dp = new DPlayer({
        container: document.getElementById('dplayer'),
        screenshot: true,
        video: {
          url: '/static/001.mp4',
          pic: '',
          thumbnails: ''
        },
        subtitle: {
          url: ''
        },
        danmaku: {
          id: 'demo',
          api: 'https://api.prprpr.me/dplayer/'
        }
      })
    },
    data(){
      return {
        // options:{
        //   container: document.getElementById('dplayer'),
        //   screenshot: true,
        //   video: {
        //     url: '/static/001.mp4',
        //     pic: '',
        //     thumbnails: ''
        //   },
        //   subtitle: {
        //     url: ''
        //   },
        //   danmaku: {
        //     id: 'demo',
        //     api: 'https://api.prprpr.me/dplayer/'
        //   }
        // }
      }
    },
    components: {
      // VueDplayer
    }
  }
</script>

<style scoped lang="stylus" rel="stylesheet/stylus">
  .d-player
    top 0
    bottom 0
    width 100%
    background-color #fff
    position absolute
</style>

```  
截图  
image  
![image](https://user-images.githubusercontent.com/16569751/37452352-4bb9709a-286f-11e8-8d04-8b75cfa46e6d.png)    
转圈的时候的控制台，并没报错  
In the console, is not an error  
![image](https://user-images.githubusercontent.com/16569751/37453063-83914400-2871-11e8-9079-52048eab28ff.png)

而且在加载的时候，弹幕加载中 这个提示语只显示了一半  
And at the time of loading, barrage loading This shows only half the clues  
![image](https://user-images.githubusercontent.com/16569751/37452450-98b61c2c-286f-11e8-8334-48334206e003.png)  
之前使用`npm run dev`跑demo报错是因为我升级node后导致的问题，但是当时我也使用`http-server`起了一个服务看的demo，结果跟现在`npm run dev`是一样的.  
  
![image](https://user-images.githubusercontent.com/16569751/37452676-3f2c0a4e-2870-11e8-9061-32751d39d94f.png)

里面并没有demo。  
请问是不是我引入Dplayer导致的问题，还是配置导致的问题。我挺喜欢DPlayer这个播放器的界面和功能的，但是试着在项目里面配了几次都不行，只有之前一次在nuxt项目中成功过，但是现在也不好使了，求帮助 _(:з」∠)_
Excuse me whether I introduce Dplayer problems or configuration problems.I quite like DPlayer this player interface and function, but try to match several times are not in the project, only once before in nuxt project merits, but also not make now, can you help me?  
不怎么会用JSFiddler，这是项目地址 [https://github.com/FirstAurora183/EXP-Mobile](https://github.com/FirstAurora183/EXP-Mobile)，可以的话能麻烦dalao down下来跑跑吗 _(:з」∠)_

**Comment by FirstAurora183** [comment]
Chrome 版本 64.0.3282.186

**Comment by XavierShi** [comment]
一个月后再回来学习dplayer，转圈的问题找到了。subtitle的url设置成了空的，于是视频中间一直有个转圈的加载图标，去掉之后就能播放视频了。不过，再一个问题就是为何固定弹幕没有居中。。这网 图片上不来了
