### ISSUE TITLE
In XiaoMi,QQ Browser, The video tag is at the top layout

### ISSUE THREAD

**Issue by SyMind** [MoePlayer/DPlayer#235]
在小米或QQ浏览器中，video标签的层级处于最顶部，无法显示弹幕和自定义控制按钮等。

**Comment by DIYgod** [comment]
It caused by browsers, I cann't do anything about it.

**Comment by SyMind** [comment]
但是bilibili网站视频播放器在这两个浏览器下是可用的，这是为什么呢？

**Comment by DIYgod** [comment]
bilibili 有白名单
