### ISSUE TITLE
目前发现一个BUG，关于hls视频播放的时候

### ISSUE THREAD

**Issue by SongChao1123** [MoePlayer/DPlayer#240]
当我在播放视频地址的时候，地址如下：https://s3.cn-north-1.amazonaws.com.cn/wlmedia/qa/live/wglive-qa_2000010041_10095_001/vod/play_1522056692480.m3u8   在4分21秒的时候会报错，Uncaught RangeError: Source is too large；
原因是我再录制视频的时候中途暂停了一会儿然后再次推流的时候，期间从https://s3.cn-north-1.amazonaws.com.cn/wlmedia/qa/live/wglive-qa_2000010041_10095_001/vod/wglive-qa_2000010041_10095_001-20180326091914-129.ts直接到https://s3.cn-north-1.amazonaws.com.cn/wlmedia/qa/live/wglive-qa_2000010041_10095_001/vod/wglive-qa_2000010041_10095_001-20180326092337-258.ts文件中出现了报错。  
但是我使用videojs-contrib-hls播放器的时候发现它其实是不会报错而且能够正常播放全程的，望作者看一下

**Comment by DIYgod** [comment]
请到[相应上游仓库](https://github.com/video-dev/hls.js/)反馈

**Comment by SongChao1123** [comment]
好的  感谢作者的关注
