### ISSUE TITLE
Is it possible to have HLS customization? 

### ISSUE THREAD

**Issue by chianhsieh** [MoePlayer/DPlayer#258]
Hello,

DPlayer use hls.js as the plugin to implement HLS, but there are lots of options and customization in HLS.
For example, I want to get the Hls's Events: MANIFEST_PARSED, but it is not possible in DPlayer.

So, is it possible to isolate the HLS as a api, so I can add some options in it.
For example:

// init the player
dp = new DPlayer();

// use the hls property which extends from the hls.js 
dp.hls.Events.MANIFEST_PARSED

I have already checked the source code in player.js
https://github.com/MoePlayer/DPlayer/blob/a16c948a2d931f0f2dd2fda904a5da27b5fedcbe/src/js/player.js

it init the hls as local varaible like:
const hls = new Hls();
hls.loadSource(video.src);
hls.attachMedia(video);

Is it possible to take hls as global property?

Thanks.

**Comment by DIYgod** [comment]
Use the second way http://dplayer.js.org/#/home?id=hls
