### ISSUE TITLE
I can‘t play the Flv demo in the Docs  with ios phone.(在ios系统的手机上无法播放 flv的demo)

### ISSUE THREAD

**Issue by bzstl** [MoePlayer/DPlayer#259]
the browser is safari(我使用的浏览器是safari)。
But the Flv demo can be played with Android phone(但是这个demo可以在安卓手机上播放)。

**Comment by kerwin-cn** [comment]
WebTorrent 也是一样

**Comment by kn007** [comment]
请不要使用Safari。换个浏览器试一下，谢谢。

**Comment by kn007** [comment]
请不要使用Safari。换个浏览器试一下，谢谢。
主要原因可能是ｄｅｍｏ防盗链了，而safari跟IE这种东西没什么区别了。

具体你可以看下： https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Browser_compatibility
因为safari不会根据新的Referrer协议传递Referrer，所以防盗链没有得到Referrer，自然就forbidden了。

**Comment by nmdx** [comment]
ios不支持mse 所以flv.js无用
