### ISSUE TITLE
在IE10很多API无法使用，例如switchVideo(),play()

### ISSUE THREAD

**Issue by no-simple** [MoePlayer/DPlayer#260]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:
使用API报错
无法获取未定义或 null 引用的属性“switchVideo”
- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
@no-simple 本项目只保证现代浏览器支持

**Comment by no-simple** [comment]
请问具体浏览器兼容性？ 只完美支持IE11？
