### ISSUE TITLE
可以即时加入清晰度切换吗？

### ISSUE THREAD

**Issue by chianhsieh** [MoePlayer/DPlayer#262]
目前清晰度的切换必须在一开始宣告时就指定了，有没有什么方式可以让它是事后再加入呢？

谢谢

The quality selection should be declared in initing the object. Is there any method so I can declare it on the fly?

Thank you

**Comment by aimhabo** [comment]
同求，小水管需要低轻

**Comment by DIYgod** [comment]
Haven't it yet
