### ISSUE TITLE
The player can not play hls files when there are some space characters in  the m3u8 file's ts  url 

### ISSUE THREAD

**Issue by player819** [MoePlayer/DPlayer#266]
#EXTINF:21.798000,
http://localhost:8181/video/userfiles/1/files/app/appVideo/2018/05/hls/aaa 0.ts
#EXTINF:20.664000,
http://localhost:8181/video/userfiles/1/files/app/appVideo/2018/05/hls/aaa 1.ts
#EXTINF:19.362000,

**Comment by A-Circle-Zhang** [comment]
try urlencode space characters
