### ISSUE TITLE
How to switch video from the live type to a normal video type? 

### ISSUE THREAD

**Issue by fancyboynet** [MoePlayer/DPlayer#268]
如何切换一个直播视频到一个普通的视频，用了switchVideo,切换成功却不会有进度条

**Comment by fancyboynet** [comment]
是我长的不够帅，所以没人理我？

**Comment by fancyboynet** [comment]
@fly3949 我现在就是删除原来的element，然后再创建一个element重新new一个播放器，直接destory后再new也会报错。。。

**Comment by DIYgod** [comment]
Can't reproduce
