### ISSUE TITLE
进度条选不中

### ISSUE THREAD

**Issue by SnakeApple** [MoePlayer/DPlayer#269]
谷歌浏览器下很难选中进度条，鼠标移动过去进度条不显示，挪开反而显示了，判定区很迷啊（好像只是中间那一块），如果要拖动就很纠结，不够人性化。。。

**Comment by kn007** [comment]
请提供问题页地址，或复现方法。
另外这个问题，你有无自己建过测试页查看呢？

这是个用户群体较大的项目。
你需要考虑为什么别人没问题，而你遇到问题。

**Comment by GuoMiaoMiao** [comment]
在嘀哩嘀哩上用谷歌浏览器看动漫确实有上面的问题
，然后我切换EDGE就正常了
DILIDILI上F12报的错：
![image](https://user-images.githubusercontent.com/28726714/40577378-3dd2bb0c-6137-11e8-9a5d-a0e5321fce6d.png)

**Comment by kn007** [comment]
@GuoMiaoMiao hmm，首先dilidili版本过旧了，与现有版本差别较大了。

其次从1.20.1版本开始，引入了promise-polyfill。或许这个版本及之后版本解决这个问题。

或许你可以尝试劫持一下，把D站的DPlayer更换为新版本后尝试。

**Comment by GuoMiaoMiao** [comment]
0.0 
我不会劫持   而且嘀哩嘀哩不是我管的

**Comment by kn007** [comment]
@GuoMiaoMiao 我只是让你跟D站站长提议。没说什么管不管的。

我说句不大好听的话，冤有头债有主。又不是DPlayer不更新。。。

浏览器的规则和协议日新月异，站点站长版本更新不及时，引起的所谓“人性化”问题，你可以选择浏览器降级去访问，尝试使用旧版本的Chrome去访问D站或许是个不错的选择。

**Comment by DIYgod** [comment]
Can't reproduction
