### ISSUE TITLE
作者大大求教弹幕功能

### ISSUE THREAD

**Issue by xkatld** [MoePlayer/DPlayer#295]
本人萌新一只，我用的是Debian 宝塔BT WordPress 使用您的 DPlayer for WordPress 插件，播放器正常播放，设置什么的都正常，就是弹幕功能有问题，一直显示弹幕加载中，弹幕可以发送出去，刷新之后弹幕不会保留。求解!

**Comment by menhood** [comment]
你可能需要把后端弹幕服务器地址设置到DIYgod的那里： https://api.prprpr.me/dplayer/

**Comment by xkatld** [comment]
就是不知道路径啊🌹
