### ISSUE TITLE
在ps4上网页观看使用Dplayer的视频的问题

### ISSUE THREAD

**Issue by zedosu** [MoePlayer/DPlayer#302]
视频中心始终有视频加载的那个点圈的第一个点在闪烁
如图
![ezgif-2-5539d77139](https://user-images.githubusercontent.com/24794186/42965805-976829ac-8bcd-11e8-8070-462ae5e90ecd.gif)

使用的是这个网站http://www.kirikiri.tv  
它用的是v1.16.0

**Comment by kn007** [comment]
不是，兄弟，你理下逻辑，你不问站长不更新DPlayer，来这开issue？

**Comment by zedosu** [comment]
@kn007  我是看到5月有两个人问了同样的问题，所以觉得应该不是版本问题。之前DIYgod说不能重现，所以我再来具体描述一下。

**Comment by kn007** [comment]
第一，升级后，复现了来提。
第二，不升级，给复现代码。

二选一，挑一个吧。
