### ISSUE TITLE
Advanced SubStation Alpha (ASS) subtitle support

### ISSUE THREAD

**Issue by Linus789** [MoePlayer/DPlayer#311]
Steps:

- Read "WrapStyle" and "ScaledBorderAndShadow"

- Read Font Styles (V4+ Styles)

- Read Dialogues (Events) [override styles if necessary and line-break option \N \n]

- Render Dialogues with SVG (necessary for smooth outline color)

- At the end it should show everything as libass or vlc would show

- Great helps: 
[moodub.free.fr/video/ass-specs.doc](http://moodub.free.fr/video/ass-specs.doc)
http://docs.aegisub.org/3.2/Styles/ http://docs.aegisub.org/3.2/ASS_Tags/
https://github.com/libass/libass

Good luck!

**Comment by Copay** [comment]
https://github.com/weizhenye/ASS

Here is a JavaScript ASS Renderer, you can do it yourself with this.

**Comment by Linus789** [comment]
Thanks. :-)
