### ISSUE TITLE
Copyright Abuse

### ISSUE THREAD

**Issue by hifocus** [MoePlayer/DPlayer#316]
https://91mjw.com/video/244.htm

As you see in this site, DPlayer is used but the copyright information in right key menu is removed.

![image](https://user-images.githubusercontent.com/30528433/44085047-fa1b436e-9fea-11e8-97cf-5e1ce5154920.png)

**Comment by DIYgod** [comment]
Thanks, but there is nothing I can do about it.

**Comment by Copay** [comment]
@hifocus
