### ISSUE TITLE
我希望该播放器可以支持下载功能像手机那样 I want the player to be able to download like a mobile phone

### ISSUE THREAD

**Issue by dxzm2013gmailcom** [MoePlayer/DPlayer#318]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
我希望你能自己写一个。
