### ISSUE TITLE
does it can auto play in chrome?

### ISSUE THREAD

**Issue by fancyboynet** [MoePlayer/DPlayer#356]

**Comment by fancyboynet** [comment]
@kn007 不好意思，因为我看chrome更新默认是不允许带音自动播放的，想问问dplayer是怎么处理这种case的
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by ikzjfr0** [comment]
@kn007 
"手机端强制不自动播放"? 
Even it's true for live play?
