### ISSUE TITLE
When I use localhost:4000 to view my site，I can't adjust video progress.

### ISSUE THREAD

**Issue by CCJohny** [MoePlayer/DPlayer#364]
当我点击进度条任意位置时都会跳回第一秒
When I click anywhere on the progress bar, it will jump back to the first second.

如果方便请使用中文答复，谢谢

**Comment by A-Circle-Zhang** [comment]
any demo?

**Comment by CCJohny** [comment]
额，就是我的视频文件放在本地的/source/videos，hexo s后localhost:4000访问直接调用，可以正常播放但调节进度无论向前向后都会重新播放，是本地资源不支持断点续传吗还是
My video file is placed in the local /source/videos, after “hexo s” and I view localhost:4000,it used my local video and can play normally, but the progress will be replayed when I adjust it both forward and backward. Is the local resource not supporting the resume?

**Comment by DIYgod** [comment]
Local video file can't be seeked.

**Comment by suwu150** [comment]
如何让播放本地视频
