### ISSUE TITLE
浏览器劫持播放器

### ISSUE THREAD

**Issue by po-lan** [MoePlayer/DPlayer#367]
在 QQ浏览器 UC浏览器中 播放器会变成浏览器的播放器
但是在 FireFox里没问题
希望可以增加一下这个屏蔽功能

**Comment by A-Circle-Zhang** [comment]
安卓下：
UC 没办法，QQ 请查阅 X5 技术文档。

**Comment by po-lan** [comment]
你有链接吗

**Comment by xoptimal** [comment]
这个现在有解决办法吗 @DIYgod
