### ISSUE TITLE
Right click 2 times to open the browser's native context menu.

### ISSUE THREAD

**Issue by EYHN** [MoePlayer/DPlayer#369]
In youtube and bilibili player. Right click 2 times will open the open the browser's native context menu.

![image](https://user-images.githubusercontent.com/13579374/44772640-fe0a3900-aba0-11e8-8c74-026eb223b0f5.png)
![image](https://user-images.githubusercontent.com/13579374/44772648-02ceed00-aba1-11e8-8882-7c3bc27fd247.png)

The chrome v69 picture-in-picture feature needs to be opened from the context menu.

![image](https://user-images.githubusercontent.com/13579374/44772907-c2bc3a00-aba1-11e8-9bde-c1fd0cdc30ad.png)

**Comment by A-Circle-Zhang** [comment]
see #285 
I think we should add a player level context menu to support picture-in-picture feature instead of showing native context menu.
for me, I think native context menu on YouTube and Bilibili player, more like a bug, not a feature.

**Comment by DIYgod** [comment]
@A-Circle-Zhang It's a feature, we made it on purpose to provide a way to show native context menu
