### ISSUE TITLE
播放视频一卡一卡的，严重影响用户体验

### ISSUE THREAD

**Issue by ZChengYuMeng** [MoePlayer/DPlayer#376]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
这关播放器什么事？

**Comment by kn007** [comment]
是不是播放的视频不够高清也要来播放器上？？？
