### ISSUE TITLE
mp4加入截屏功能时无法播放

### ISSUE THREAD

**Issue by sishen520** [MoePlayer/DPlayer#388]
一直播放不出来mp4视频，测试了几个小时，终于找出了问题。
播放mp4视频如果加入这一行，播放时直接显示播放失败
`screenshot: true,`
取消则正常播放
例如：
[http://jx.xcsee.cn/4.php](url)可正常播放。
[http://jx.xcsee.cn/5.php](url)播放失败。
只多加入了一行上方的截屏代码。

**Comment by DirectLinkSs** [comment]
仔细看说明需要开启跨域。
