### ISSUE TITLE
开启ssl使用https访问时播放hls资源失败

### ISSUE THREAD

**Issue by sishen520** [MoePlayer/DPlayer#390]
如题，举例：
`https://jx.xcsee.cn/dp.php?url=https://me.guiji365.com/20181008/vlopkLNe/index.m3u8`
使用http访问正常。

**Comment by kn007** [comment]
兄弟，你能不能先找下自己问题，每次开issue会通知很多人，懂么。很骚扰的
浏览器已经告诉你This request has been blocked; the content must be served over HTTPS.
