### ISSUE TITLE
点击播放和音量以外的所有按钮，url会被添加参数导致页面刷新

### ISSUE THREAD

**Issue by Nolin-Lin** [MoePlayer/DPlayer#403]
环境：
PC chrome 70.0.3538.77（正式版本）
vue-cli 3.0
dplayer 1.25.0

代码：
```
<div id="dplayer"></div>

import 'dplayer/dist/DPlayer.min.css';
import DPlayer from 'dplayer';

const dp = new DPlayer({
   container: document.querySelector('#dplayer'),
   video: {
      url: 'http://static.smartisanos.cn/common/video/t1-ui.mp4',
      pic: 'http://static.smartisanos.cn/pr/img/video/video_03_cc87ce5bdb.jpg'
   },
});
```
第一步：
打开url： `http://localhost:8080/#/edit?id=71`
第二步：
点击设置按钮
url 变成 
`http://localhost:8080/?file=&dplayer-danmaku-color-0=%23fff&dplayer-danmaku-type-0=0&dplayer-toggle-dan=on#/edit?id=71`

希望有大佬可以帮我解答一下问题，谢谢

**Comment by Nolin-Lin** [comment]
使用 element-ui 的 el-dialog, 当 el-dialog 打开时
```
<el-dialog :visible.sync="videoDialogVisible" title="视频截图" ref="videoDialog" @opened="op"></el-dialog>
op() {
      const dp = new DPlayer({
        container: document.querySelector('#dplayer'),
        video: {
          url: 'http://static.smartisanos.cn/common/video/t1-ui.mp4',
          pic: 'http://static.smartisanos.cn/pr/img/video/video_03_cc87ce5bdb.jpg'
        }
      });
    }
```

**Comment by Nolin-Lin** [comment]
在 element-ui 的 el-from 里面使用 DPlayer
使用右侧的功能按键的时候会，提交表单，具体原因不明

**Comment by yuzhengbo** [comment]
> 在element-ui的el-from里面使用DPlayer
> 使用右侧的功能按键的时候会，提交表单，具体原因不明

遇到了同样的问题

**Comment by LoveYou3000** [comment]
Dplayer V1.27.0 依旧存在这个问题

**Comment by LoveYou3000** [comment]
> > 在element-ui的el-from里面使用DPlayer
> > 使用右侧的功能按键的时候会，提交表单，具体原因不明
> 
> 在form上，加@submit.native.prevent，可以解决

那不是form呢 怎么解决啊
