### ISSUE TITLE
when the page have video element  and more then one ,d-palyer will play and pause over and over

### ISSUE THREAD

**Issue by abaozhizhong** [MoePlayer/DPlayer#405]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

 bug:

when the page have video element  and more then one ,d-palyer will play and pause over and over

**Comment by abaozhizhong** [comment]
> 中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。
> 
> bug:
> 
> when the page have video element and more then one ,d-palyer will play and pause over and over

**Comment by langerc** [comment]
How did you resolve the problem i have exactly the same.

**Comment by edward8628** [comment]
just call event.stopImmediatePropagation() at end of the event listener
