### ISSUE TITLE
BUG。全屏不能拉伸画面！网页全屏无用

### ISSUE THREAD

**Issue by xinggsf** [MoePlayer/DPlayer#407]
这样的全屏真的没用！网页全屏按钮干脆就没用！！

**Comment by A-Circle-Zhang** [comment]
发一个你的演示页面吧。

**Comment by xinggsf** [comment]
@A-Circle-Zhang 
[安装浏览器脚本](url=https://bbs.kafan.cn/thread-2135873-1-1.html)
随便看个[课程](url=http://open.163.com/movie/2017/6/6/T/MCL8DCPJT_MCL8DP46T.html)
