### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by BaiMingxu** [MoePlayer/DPlayer#411]
本人小白一枚，求大佬帮忙？我这样写缺了什么？怎么页面上什么都没有？
<img width="663" alt="_20181107221214" src="https://user-images.githubusercontent.com/22886455/48136349-6761a300-e2da-11e8-8467-f94cad6cc540.png">

**Comment by xincmm** [comment]
看样子，你把脚本文件写在了<head> 标签里，你得去了解一下浏览器 JavaScript 的执行顺序，如果非要写在 <head> 标签里面的话，需要设置<script>延迟加载，不然就将脚本写在 </body> 结束标签之前。
