### ISSUE TITLE
Adding video size parameters. 

### ISSUE THREAD

**Issue by findwisdom** [MoePlayer/DPlayer#413]
添加视频大小参数
在视频加载前显示文字，此视频流量大约为多少MB或者GB，请在wifi下观看土豪请无视。
举例
video size : '800MB',
或者 
video size : '1.5GB',

Adding video size parameters. 
Display text before the video load, this video traffic is about how many MB or GB, to watch tuhao on wifi please ignore.
For example, 
video size: '800MB',
video size:' 1.5GB',

**Comment by bidiu** [comment]
感觉这个应该算是自定义功能，自己实现的话也不是很复杂，个人感觉不需要内置在player中
