### ISSUE TITLE
能否添加个插件 支持多个视频分段的视频 比如一个视频20分钟分成5分钟一个  把四个合并成一个的

### ISSUE THREAD

**Issue by hkchenhongyi** [MoePlayer/DPlayer#417]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by ncc0706** [comment]
@DIYgod 支不支持你倒是说啊

**Comment by kn007** [comment]
@ncc0706 你这什么态度呢。
注意你的说话方式。

**Comment by ncc0706** [comment]
@kn007 你认识我

**Comment by A-Circle-Zhang** [comment]
建议不要盗链视频网站的视频

**Comment by ncc0706** [comment]
既然是国产的货，就应该对内支持好点，是不是就close，有毛用

**Comment by kn007** [comment]
我对认识脑残痴呆没什么兴趣，谢谢。

**Comment by ncc0706** [comment]
哪个傻逼@老子了，就会装逼，你有什么能耐啊

**Comment by ncc0706** [comment]
你他娘的有种别说中文啊

**Comment by kn007** [comment]
为啥都是山东，你就特别垃圾呢
既然你那么喜欢，怎么不见你赞助呢

**Comment by kn007** [comment]
你有种就别伸手啊，自己写啊

**Comment by ncc0706** [comment]
看你的贡献才13次就是打酱油的，装什么大佬

**Comment by kn007** [comment]
我说我是大佬了么？是不是大佬需要说出来的么
呵呵

**Comment by ncc0706** [comment]
把开源项目做好就好了，整天就会吓逼逼

**Comment by kn007** [comment]
好不好也轮不到你来说，寄生虫，你又做了什么贡献？

**Comment by ncc0706** [comment]
你算个屌啊

**Comment by kn007** [comment]
是是是，我不算什么。我反正是个人。

简单说，人家不愿意回答，你这种一句话说你倒是说啊。
你算什么？

而且开源，举个不算恰当的比喻，就是把自己东西分享给大家。
你不能为之感激，不能为之添砖加瓦。起码伸手时，也别那么无礼，谁也不欠你的。

你如果是付费定制业务，双方同意，开发方没做到，你这种态度，大家都是人，谁也不舒服。但有合同，起码理亏。
但你没有为此付出什么，只是伸手，你有要求，别人不搭理，你就开始站在制高点，不礼貌了？
不知你是缺少教育，还是缺乏人性。

**Comment by DIYgod** [comment]
block + report

![](https://i.loli.net/2019/06/27/5d141d13eca4474069.jpg)
