### ISSUE TITLE
第三方MP4 提示跨域问题

### ISSUE THREAD

**Issue by wuyawei** [MoePlayer/DPlayer#426]
第三方MP4源 直接用type:auto提示跨域，但是用hls后再用f12直接改src 是可以播放的（），视频源用vlc播放器也是可以播放的

**Comment by A-Circle-Zhang** [comment]
演示呢

**Comment by a398496800** [comment]
哈哈哈，我也是。我是WP建站出现的这个问题。后来研究发现，其实是DPlayer版本的问题，你播放器上应该是有一个字幕功能，这个字幕功能会导致开启一个东西。这个东西我不懂，只知道这东西开了你就不能用第三方。你可以参考一下
