### ISSUE TITLE
求大佬！hls视频流离开页面后还一直请求数据

### ISSUE THREAD

**Issue by wuyawei** [MoePlayer/DPlayer#427]
hls直播流离开播放页面后，还会一直请求视频流，销毁播放器都不行

**Comment by haoyunmanbu** [comment]
```javascript
const hls;
const dp = new DPlayer({
    container: document.getElementById('dplayer'),
    video: {
        url: 'demo.m3u8',
        type: 'customHls',
        customType: {
            'customHls': function (video, player) {
                hls = new Hls();
                hls.loadSource(video.src);
                hls.attachMedia(video);
            }
        }
    }
});
路由或者页面卸载的时候：
hls.destory();   [说明](https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams)
dp.destroy();

```

**Comment by 0LING0** [comment]
> 



> ```js
> const hls;
> const dp = new DPlayer({
>     container: document.getElementById('dplayer'),
>     video: {
>         url: 'demo.m3u8',
>         type: 'customHls',
>         customType: {
>             'customHls': function (video, player) {
>                 hls = new Hls();
>                 hls.loadSource(video.src);
>                 hls.attachMedia(video);
>             }
>         }
>     }
> });
> 路由或者页面卸载的时候：
> hls.destory();   [说明](https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams)
> dp.destroy();
> ```
hls.destory() 会报destroy() is not a function的错误

**Comment by 0LING0** [comment]
> ```js
> const hls;
> const dp = new DPlayer({
>     container: document.getElementById('dplayer'),
>     video: {
>         url: 'demo.m3u8',
>         type: 'customHls',
>         customType: {
>             'customHls': function (video, player) {
>                 hls = new Hls();
>                 hls.loadSource(video.src);
>                 hls.attachMedia(video);
>             }
>         }
>     }
> });
> 路由或者页面卸载的时候：
> hls.destory();   [说明](https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams)
> dp.destroy();
> ```

是hls.destroy()，单词写错了
