### ISSUE TITLE
大佬，有discuz插件吗，直接安装就能用的！

### ISSUE THREAD

**Issue by llssjjcom** [MoePlayer/DPlayer#428]
大佬，有discuz插件吗，直接安装就能用的！

**Comment by asleep2** [comment]
同求，现在一直用的方法是在dz帖子编辑里用iframe嵌套 dplayerP2P的demo.html  太麻烦了呃

**Comment by 1265578519** [comment]
@asleep2 iframe方式你回帖多个播放器测试过吗，，好用我也搞一个

**Comment by asleep2** [comment]
@1265578519 麻烦，而且一个页面如果视频多了就会很卡。

**Comment by 1265578519** [comment]
http://bbs.itzmx.com/thread-93523-1-1.html @asleep2 我抽时间写了个，，，你想要的话，可以试试，模板化的当然只有mp4。
