### ISSUE TITLE
播放器你手机端不能横屏的问题

### ISSUE THREAD

**Issue by xiaoming0827** [MoePlayer/DPlayer#429]
使用dplayer播放器播放视频后，点击全屏，在手机方向锁定的情况下，播放器只能竖屏，不能做到全屏横屏播放，请问如何解决这个问题，十分感谢

**Comment by forTribeforXuanmo** [comment]
我也是这个问题 咋搞 设置web模式也不行啊

**Comment by a624669980** [comment]
没人回复吗

**Comment by kn007** [comment]
...你们是不是想当然了。要移动端系统支持，而不是单靠播放器解决的。

**Comment by darkgirl** [comment]
> ...你们是不是想当然了。要移动端系统支持，而不是单靠播放器解决的。

能不能全屏播放的时候把画面旋转90度呢

**Comment by kn007** [comment]
那人家是平板呢？
人家开了自动旋转，打横了呢？
不要想当然

**Comment by unkaer** [comment]
找到方案了，前来回帖。但好像要支持H5的手机浏览器，现在主流浏览器都支持。

``` html
//手机全屏自动横屏
var isMobile = !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/);
if (isMobile) {
    //全屏事件
    console.log('isMobile1');
    dp.on('fullscreen',function() {
        screen.orientation.lock("landscape");
    });
    //退出全屏事件
    dp.on('fullscreen_cancel',function() {
        screen.orientation.unlock();
    });
}
```

**Comment by hktrace** [comment]
dp.on('fullscreen', function() {
	       var isMobile = !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/);
                if (isMobile) {
                    //全屏事件
                    screen.orientation.lock("landscape");
                }
   });
    //监听播放器退出全屏事件并触发强制竖屏
   dp.on('fullscreen_cancel', function() {
               var isMobile = !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/);
                if (isMobile) {
                    //退出全屏事件
                    screen.orientation.unlock();
                }
   });

**Comment by TaiYou1026** [comment]
@hktrace @unkaer  感谢提供方法很管用。
@kn007 另外，不知道你是个什么东西，哔哩吧啦的啥也不是，出来恶心人。

**Comment by kn007** [comment]
@TaiYouWeb 首先我是个人，至于你，首先不说你挖多久前的坟有没有好好看。
你连上下文都不会看，也不会看看想想当时是否存在有解决方案。
你好好看上下文再说话吧，而且这一开口，真厉害。
