### ISSUE TITLE
How to use in a component of the react project？

### ISSUE THREAD

**Issue by qdhaiqiang** [MoePlayer/DPlayer#432]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by qdhaiqiang** [comment]
I'm in [ant design pro ](https://ant.design/docs/react/introduce-cn) project，my component like this：
`import React, { PureComponent } from 'react';
import 'DPlayer/dist/DPlayer.min.css';
import DPlayer from 'DPlayer';

export default class VideoJsPlayer extends PureComponent {
  constructor() {
    super()
    this.state = {
      videoJsOptions: {
        screenshot: true,
        video: {
            url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
            pic: 'https://github.com/video-react/video-react/blob/master/docs/static/poster.png',
            thumbnails: 'thumbnails.jpg',
            type: 'auto'
        },
        subtitle: {
            url: 'webvtt.vtt'
        },
        danmaku: {
            id: 'demo',
            api: 'https://api.prprpr.me/dplayer/'
        }
      }
    }
  }

  render() {
    const dp = new DPlayer(this.state.videoJsOptions);
    return (
      <div className="player">
        dp
      </div>
    )
  }
}
`
Now, I don't know how to use this dp const in render function.
Thanks

**Comment by coder-xsy** [comment]
just use Dplayer as a Componetn,then things like video and danmaku are its properties;just set like:
`<Dplayer
                            ref="dplayer"
                            video={{
                                url: 'xxxx',
                                pic: xxxxx
                            }}
                            danmaku={{
                                id: 'xxxxx',
                                api: 'xxxxx'
                            }}
                        />`
