### ISSUE TITLE
IOS设备无法正常播放flv格式视频

### ISSUE THREAD

**Issue by paysen-z** [MoePlayer/DPlayer#434]
IOS设备无法正常播放flv格式视频，提示 can't find flvjs   视频加载失败，官方demo也是这样的情况
![_20181220164301](https://user-images.githubusercontent.com/11954497/50273933-ea981c00-0476-11e9-96e7-53ee73838a49.jpg)

**Comment by TomLao** [comment]
引入支持flv的js文件，官方文档上有写。
<script src="https://cdn.bootcss.com/flv.js/1.5.0/flv.js"></script>

**Comment by payson-z** [comment]
都有加引入的，在手机上访问还是不行，演示地址：http://player.uucweb.com/?url=http://player.uucweb.com/flv/1.flv

![_20181220183639](https://user-images.githubusercontent.com/11954497/50280506-acefbf00-0487-11e9-98c1-3f40eaf66520.png)

**Comment by TomLao** [comment]
> 都有加引入的，在手机上访问还是不行，演示地址：http://player.uucweb.com/?url=http://player.uucweb.com/flv/1.flv
> 
> ![_20181220183639](https://user-images.githubusercontent.com/11954497/50280506-acefbf00-0487-11e9-98c1-3f40eaf66520.png)

视频的type没加上。

**Comment by TinkoLiu** [comment]
> > 都有加引入的，在手机上访问还是不行，演示地址：http://player.uucweb.com/?url=http://player.uucweb.com/flv/1.flv
> > ![_20181220183639](https://user-images.githubusercontent.com/11954497/50280506-acefbf00-0487-11e9-98c1-3f40eaf66520.png)
> 
> 视频的type没加上。

iOS Safari 不支持 Media Source Extension ，请不要误导
