### ISSUE TITLE
在iframe里面。web 全屏无效？

### ISSUE THREAD

**Issue by dxhuii** [MoePlayer/DPlayer#439]
如果在iframe无法实现全屏，那么，web全屏，怎么取消，或者隐藏掉呢？

**Comment by rainforyou** [comment]
http://dplayer.js.org/#/home?id=why-cant-player-be-full-screen

**Comment by dxhuii** [comment]
> http://dplayer.js.org/#/home?id=why-cant-player-be-full-screen

我说是网页全屏，不是全屏。
