### ISSUE TITLE
检测到m3u8文件无法读取时，该如何触发条件？

### ISSUE THREAD

**Issue by dickzhenhua** [MoePlayer/DPlayer#446]
比如一个本地的m3u8文件（http://127.0.0.1/123.m3u8）是不存在的，但使用事件绑定并不能触发到提示，代码如下：

dp.on('error', function () {
    alert("这个文件是错误或不存在的！");  	
});

请问这个错误提示信息该如何写才能触发？

**Comment by haoyunmanbu** [comment]
```
需要hls库的方法
https://github.com/video-dev/hls.js/blob/master/docs/API.md#fifth-step-error-handling
```

**Comment by lqzhgood** [comment]
根据 HLS 的文档。 error 事件需要挂载在 hls 实例上。
```
 hls.on(Hls.Events.ERROR, function (event, data) {
   ...
  });
```
hls 实例好像并没有暴露出来。 是不是只有提 PR 把 HLS挂到 dp 实例上 才能解决这个问题呢？
https://github.com/MoePlayer/DPlayer/blob/ecc241115bd5dd5a76ed914a168d3467031bd6f1/src/js/player.js#L346

**Comment by wanglong126** [comment]
很有帮助,感谢
