### ISSUE TITLE
貌似弹幕API炸了

### ISSUE THREAD

**Issue by xtgjzwj** [MoePlayer/DPlayer#447]
可以公开接口API文件吗？这样我们就可以自己建弹幕系统了，而且不用吃您的服务器。。

**Comment by menhood** [comment]
@xtgjzwj https://github.com/MoePlayer/DPlayer-node 了解一下

**Comment by xtgjzwj** [comment]
我被docker搞蒙了，node有办法折腾不

**Comment by menhood** [comment]
你可以研究下源码，我只会按照说明配置 ~~菜的抠脚~~

**Comment by coder-xsy** [comment]
使用弹幕的API无效，这个不知道如何解决？

**Comment by menhood** [comment]
https://github.com/MoePlayer/DPlayer-node 自建 或者用其他网友搭建的后端

**Comment by oyjcmyn** [comment]
如果自己会点后端，自己可以直接写个。我就是直接用PHP自己写了自己用
