### ISSUE TITLE
 Chrome 72 Fullscreen doesn't work 

### ISSUE THREAD

**Issue by unknownplace** [MoePlayer/DPlayer#448]
- Which versions of DPlayer, and which browser / OS are affected by this issue?
windows10,chrome 72, DPlayer 1.24.0

![1](https://user-images.githubusercontent.com/34019161/52736525-03e7bf80-3005-11e9-9f13-72ba6f2de0a7.png)
![2](https://user-images.githubusercontent.com/34019161/52736526-03e7bf80-3005-11e9-915d-6caa30c96835.png)

**Comment by kn007** [comment]
不能复现。

**Comment by unknownplace** [comment]
可能是这个版本有问题,在源码里都找不到未压缩的版本,是在一个盗版电影网站上的,,
https://cdn.bskchina.cn/dplayer/dplayer.js

**Comment by unknownplace** [comment]
可能是这个版本有问题,我也试了你的没问题
https://cdn.bskchina.cn/dplayer/dplayer.js

**Comment by kn007** [comment]
你这个是1.24.0 cd6afd7版本，1.24.0 release版本是ce2e8da。
而目前最新版本为1.25.0 d20b243，release版本为fdcf45b。
中间有一些commit没更新到，即便有问题也不足为奇。

**Comment by kn007** [comment]
以上，不属于本项目问题，请自行关闭issue。
