### ISSUE TITLE
文档打不开了

### ISSUE THREAD

**Issue by axhello** [MoePlayer/DPlayer#450]
http://dplayer.js.org/#/zh-Hans/

**Comment by lidedongsn** [comment]
https
https://dplayer.js.org/#/zh-Hans/

**Comment by menhood** [comment]
@lidedongsn 可能你需要搭个梯子或者换个dns服务商 🌚

**Comment by lidedongsn** [comment]
> @lidedongsn 可能你需要搭个梯子或者换个dns服务商

我的意思是http的 chrome是打不开  用https能打开

**Comment by axhello** [comment]
@lidedongsn @menhood 
![image](https://user-images.githubusercontent.com/10368684/53470475-b9525280-3a9c-11e9-8fa9-db72edf2eb64.png)

然而还是不行

**Comment by axhello** [comment]
@lidedongsn @menhood 知道什么原因了 chrome扩展Vue.js devtools 跟网站冲突报错了
