### ISSUE TITLE
can not play m3u8 format on Android

### ISSUE THREAD

**Issue by douxz** [MoePlayer/DPlayer#471]
![1](https://user-images.githubusercontent.com/38687941/55939514-8214bb00-5c70-11e9-805b-2ca0f12e8e85.png)
![2](https://user-images.githubusercontent.com/38687941/55939518-84771500-5c70-11e9-83db-7e69c8d667d4.png)

**Comment by haoyunmanbu** [comment]
@douxz 应该需要引入hls库

**Comment by SchulzJak** [comment]
解决了吗，我也遇到这个问题，ios和Windows端都可以播放，但是安卓播放不了

**Comment by ekworp** [comment]
customType
