### ISSUE TITLE
正在加载播放中,请稍等...

### ISSUE THREAD

**Issue by bobcatss** [MoePlayer/DPlayer#475]
<img src="https://ws3.sinaimg.cn/large/005BYqpgly1g26rht8tvgj30rc0dpjrb.jpg"/>
这台电脑flash安装了最新版本都加载不出来。网络没问题，其他电脑可以播放。
这种情况要怎么解决？所有浏览器都这样。

**Comment by kn007** [comment]
首先这关flash啥关系，而且这又是啥网站。关DPlayer什么事。。。

**Comment by kn007** [comment]
网站问题找站长好吧，不要什么问题都来找播放器。
