### ISSUE TITLE
是否支持播放RTMP流

### ISSUE THREAD

**Issue by MX12306** [MoePlayer/DPlayer#480]
是否支持播放RTMP流

**Comment by AnyMoe** [comment]
**DPlayer supports:**

- Streaming formats
    - [HLS](https://github.com/video-dev/hls.js)
    - [FLV](https://github.com/Bilibili/flv.js)
    - [MPEG DASH](https://github.com/Dash-Industry-Forum/dash.js)
    - [WebTorrent](https://github.com/webtorrent/webtorrent)
    - Any other custom streaming formats
- Media formats
    - MP4 H.264
    - WebM
    - Ogg Theora Vorbis

A good idea for live is that you can convert rtmp stream to flv stream and play with flv.js.

**Comment by huanghe2015** [comment]
RTMP必须依赖Flash
