### ISSUE TITLE
dplayer 播放没音轨的视频 全屏切换的时候 很大几率出现无限暂停

### ISSUE THREAD

**Issue by hkchenhongyi** [MoePlayer/DPlayer#487]
dplayer 播放没音轨的视频 全屏切换的时候 很大几率出现无限暂停/播放 切换

测试环境谷歌浏览器  默认最新版本

测试了一下video标签播放没音轨的视频 只要选项卡不在当前页面 视频就会暂停  有可能是这个原因！

**Comment by lrbmike** [comment]
我这边也出现了无限暂停/播放 切换的情况，但是是按空格键的时候就会出现

**Comment by quickfight** [comment]
问题类似 @lrbmike 说的，初步看代码是播放器加载后，监听<video/>的play和pause，然后调用自身的play/pause函数，在函数内部又调用了video.play和video.pause，造成循环。但是不明白，为什么刚加载的时候没事，随便点一点，进行个resize就会出现了

**Comment by DIYgod** [comment]
Duplicate of #487

**Comment by DIYgod** [comment]
Duplicate of #500
