### ISSUE TITLE
双击播放器很大概率无限暂停

### ISSUE THREAD

**Issue by Jackzyy** [MoePlayer/DPlayer#497]
谷歌浏览器   版本 75.0.3770.100（正式版本） （64 位）
双击播放器很大概率会出现播放和暂停无限切换

**Comment by kn007** [comment]
同版本Chrome，win10，无此问题。
无法复现。

**Comment by DIYgod** [comment]
Duplicate of #542

**Comment by DIYgod** [comment]
Duplicate of #500
