### ISSUE TITLE
how to setting fullscreen

### ISSUE THREAD

**Issue by mcmf** [MoePlayer/DPlayer#499]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
```
<template>
  <div class="page-dplayer">
    <div id="dplayer"></div>
    <div>参与人数：10010</div>
  </div>
</template>

<script>
import 'dplayer/dist/DPlayer.min.css';
import DPlayer from 'dplayer';

export default {
  name: 'dplayer',

  mixins: [],

  components: {},

  data() {
    return {
      video:{
        isLive:true,
        url:'h.m3u8',
        type:'hls',
        pic:'snap.jpg',
      }
    };
  },

  computed: {},

  watch: {
    
  },

  created() {
  },

  mounted() {
    const dp = new DPlayer({
      container: document.getElementById('dplayer'),
      live: this.video.isLive,
      danmaku: false,
      video:this.video
    });
  },

  destroyed() {
  },

  methods: {
    play(){
      dp.toggle()
    }
  }
}
</script>

<style lang="less" rel="stylesheet/less" scoped>
  @import "./style.less";
</style>

```
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
no 
- Which versions of DPlayer, and which browser / OS are affected by this issue?
ios and android

会出现两个全屏icon，参数里没有找到关闭设置 ,请问在哪里设置 
![image](https://user-images.githubusercontent.com/19700237/60000067-0c789280-9696-11e9-9342-99064204272d.png)

**Comment by kn007** [comment]
请完整表达清楚问题。
你是不想要全屏按钮？这两个按钮，一个是窗口放大，一个是全屏放大。（移动端因为各家的问题，对非内置播放器支持一般，任何第三方播放器，放大都是没有全屏，如果你自己不切换方向的话）
我记得不能配置为无全屏按钮，具体看doc

**Comment by mcmf** [comment]
已经解决了

**Comment by iponkan** [comment]
> 已经解决了

请问下怎么解决的，可以分享下吗，我也想配置成无全屏按钮

**Comment by gzlock** [comment]
@iponkan 应该是用了css将全屏按钮隐藏吧

**Comment by iponkan** [comment]
> @iponkan 应该是用了css将全屏按钮隐藏吧

我也是这个想法，但可能对css不熟悉所以没找到(╯▽╰)╭  @gzlock

**Comment by gzlock** [comment]
> > @iponkan 应该是用了css将全屏按钮隐藏吧
> 
> 我也是这个想法，但可能对css不熟悉所以没找到(╯▽╰)╭ @gzlock

可以试试[我的播放器，Demo](https://gzlock.github.io/danplayer)，可以通过设置禁用全屏功能(同时隐藏了全屏按钮)

**Comment by iponkan** [comment]
> > > @iponkan 应该是用了css将全屏按钮隐藏吧
> > 
> > 
> > 我也是这个想法，但可能对css不熟悉所以没找到(╯▽╰)╭ @gzlock
> 
> 可以试试[我的播放器，Demo](https://gzlock.github.io/danplayer)，可以通过设置禁用全屏功能(同时隐藏了全屏按钮)

嗯嗯，其他按钮可以隐藏吗。我想影响弹幕那些，因为暂时还不需要

**Comment by gzlock** [comment]
> 嗯嗯，其他按钮可以隐藏吗。我想影响弹幕那些，因为暂时还不需要
@iponkan 按你的需求修改了我的播放器逻辑，最新版0.0.24已经可以显示 / 隐藏【弹幕显示/隐藏按钮】
可以达到这样极简的界面
![image](https://user-images.githubusercontent.com/2311740/65615121-6e28ff80-dfeb-11e9-90d4-58e61cd79cbf.png)

**Comment by iponkan** [comment]
> > 嗯嗯，其他按钮可以隐藏吗。我想影响弹幕那些，因为暂时还不需要
> 
> @iponkan 按你的需求修改了我的播放器逻辑，最新版0.0.24已经可以显示 / 隐藏【弹幕显示/隐藏按钮】
> 可以达到这样极简的界面
> ![image](https://user-images.githubusercontent.com/2311740/65615121-6e28ff80-dfeb-11e9-90d4-58e61cd79cbf.png)

好的，我修改css也可以了，但也希望能用下你的播放器，因为这个播放器其他自定义的东西暂时还找不到入口。给你gmail发邮件了，播放器的问题希望能请教请教 @ @gzlock
