### ISSUE TITLE
视频在resize和全屏时某些浏览器会在play/pause之间来回切换，陷入死循环

### ISSUE THREAD

**Issue by quickfight** [MoePlayer/DPlayer#500]
MacBook Pro Chrome 74.0.3729.169
dplayer version 1.2.50
commit 4adab30fcb1d9b57b54ddf7c023eb20e8b3ec2db
我debug了代码，在player.js.initVideo函数的481行，对video绑定了play事件，该事件触发了173行的play()函数，该函数内部又调用了video.play()函数，该函数又触发了video的play事件，导致死循环。pause貌似也有同样的问题。
估计大多数浏览器对于重复的play事件有屏蔽处理，所以没有此问题。但是碰巧我的浏览器不知什么原因导致这个现象。我将181行和213行关于play和pause的函数调用相关代码注释掉后，就正常了。但是点击屏幕已经不能进行play/pause切换了。
希望能得到帮助，谢谢。

related#487

**Comment by quickfight** [comment]
貌似不再维护了？这么严重的bug不解决。。。算了，我自己改源代码去吧

**Comment by ncc0706** [comment]
@quickfight 人家让你发英文，你非得发中文，碰鼻子了吧

**Comment by kn007** [comment]
没有Mac，无法复现。
方便录个视频么？

我用DPlayer-Lite，不同实例切来切去，通过空白键，播放器按钮暂停播放很正常。。
https://kn007.net/topics/legends-never-die/

**Comment by quickfight** [comment]
@kn007 非常感谢你的回答，视频用百度网盘是否可以？
https://pan.baidu.com/s/1etZwK5TLGPog1xfHHsqUQg 提取码: 3c3r

**Comment by quickfight** [comment]
补充：用的是flv直播流
flv.js:1.5.0

**Comment by kn007** [comment]
兄弟，真的是。。。有耐心，我看看
其他来源有问题么，我拿hls的试一下。

**Comment by kn007** [comment]
event对play和pause动作直接加console，不就好了么？

**Comment by kn007** [comment]
[20190701_210549.zip](https://github.com/MoePlayer/DPlayer/files/3346491/20190701_210549.zip)

 我测试了是没问题。。。（3小时前没评论成功）

**Comment by quickfight** [comment]
@kn007 好的，我增取抽出个demo出来

**Comment by quickfight** [comment]
@kn007 经过多台电脑测试，目前仅发现在mac上100%复现，windows很难观察到，我准备了复现的demo地址：
[http://play.edupj.org](url)
在mac上，用最新版chrome打开网址，打开console，来回resize，全屏几次就会出现。
源代码如下
[http://play.edupj.org/dplayer_test_20190702.zip](url)
重现视频如下
[http://play.edupj.org/无限暂停重现录屏.mov](url)

**Comment by kn007** [comment]
如果不用chrome呢，其他浏览器呢。。
没有MAC。。。帮不到你怕是。

**Comment by Jackzyy** [comment]
> @kn007 经过多台电脑测试，目前仅发现在mac上100%复现，windows很难观察到，我准备了复现的demo地址：
> http://play.edupj.org
> 在mac上，用最新版chrome打开网址，打开console，来回resize，全屏几次就会出现。
> 源代码如下
> [demo代码](http://play.edupj.org/dplayer_test_20190702.zip)
> 重现视频如下
> [重现录屏](http://play.edupj.org/%E6%97%A0%E9%99%90%E6%9A%82%E5%81%9C%E9%87%8D%E7%8E%B0%E5%BD%95%E5%B1%8F.mov)

的确是有这个问题，我这边谷歌浏览器也是 暂停和播放无限切换，我后来修复了一下这个BUG，不过时间比较长，忘记修改的哪一行了，如果需要我可以发你一份修改后的JS，你可以对比下

**Comment by kn007** [comment]
你可以发下，我回头看看

**Comment by kn007** [comment]
@Jackzyy 你好，方便发一下么？

**Comment by kt286** [comment]
Window7 Firefox浏览器 点开 quickfight 提供的demo 切换到别的标签页 过一会就会复现

**Comment by wangxingkang** [comment]
npm 最新版本是有问题的， 代码已经修复了  可是 为啥 不发布新的版本

**Comment by DIYgod** [comment]
e3a4631695c45f096e92e7f6cbb03e7ce2243909
