### ISSUE TITLE
How to destory dplayer on live mode?

### ISSUE THREAD

**Issue by tuanzisama** [MoePlayer/DPlayer#501]
As you know. Dplayer add a new API on [1e21471](https://github.com/MoePlayer/DPlayer/commit/1e21471519c5bdf93252d0e497fcbbce9f727c94) `dp.destroy()`

I try use this API on `beforeDestroy` call `dp.destroy()` ,also use `v-if` destory this DOM instance, but Network Panel(Chrome DevTools) still making requests continuously.

What should i do...

Config : `video: { url: 'http://example.com/live.m3u8', type: 'hls' } `
Google Chrome | 75.0.3770.100 （64 bit） (cohort: Stable)
Windows 10,  Vue ^2.5.10

**Comment by kn007** [comment]
或许是用了hls的原因？你试试正常mp4会不会。
如果hls的问题话，可能要看下上游的问题。可能销毁DPlayer前，你需要先对hls做销毁。

**Comment by tuanzisama** [comment]
谢谢，我在这里就说中文了。

mp4的播放格式我尝试了一下并未出现我提及的问题。
我查看了hls.js的[API](https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams)
`
Final step: destroying, switching between streams
hls.destroy() should be called to free used resources and destroy hls context.
`

但是似乎需要Dplayer内部创建的Hls实例才允许触发destroy。
Dplayer内部的Hls实例在何处可以被调用...
请帮助我，非常感谢。

**Comment by tuanzisama** [comment]
查阅dplayer代码时
发现在/src/js/player.js:346
将此处定义的`hls`赋值到window，然后通过window来调用这个映射出去的hls实例进行destroy
` const hls = new Hls(); `

不知道开发人员可否将此hls实例赋值到一些全局变量上方便开发，我这里暂时的解决方案只能是用下载好的`dplayer.min.js`手动修改压缩后代码，将其映射到window中

---
顺便提供这个问题 **未修复的情况下** _治标不治本_ 的解决方案
并且不要修改通过npm/yarn等包管理工具拉回的dplayer， **一定要用自己下载的！** 

搜索`var i=new Hls;`
在`;`后添加`window.dplayerHls = i;`
然后可以在window中进行使用Hls的API

**Comment by kn007** [comment]
@tuanzisama 方便测试一下么，调用DPlayer的destroy就好了

[test501.zip](https://github.com/MoePlayer/DPlayer/files/3345322/test501.zip)

**Comment by kn007** [comment]
讲道理，我不添加其他扩展destroy，请求也会终止。。。
因为我不是通过直播方式，不知道有没有关系。

**Comment by tuanzisama** [comment]
我刚才在网上找到了一个m3u8地址试了一下 hls的请求停止了

但当我使用项目中的m3u8时 则不能被销毁

**Comment by kn007** [comment]
用了我给你的zip了么？
你录像给我看加network标签

**Comment by tuanzisama** [comment]
新的[#508](https://github.com/MoePlayer/DPlayer/pull/508) 包我放到项目中成功cancel了我自己的m3u8地址请求

![image](https://user-images.githubusercontent.com/33369729/60479013-e61aae80-9cb6-11e9-91ad-ea3fecfd3537.png)

**Comment by kn007** [comment]
那就是我的zip啊。。你也可以拿下508自己编译，现在还没合并到master，你直接抓master代码没用的

**Comment by tuanzisama** [comment]
508包已经解决了 [comment](https://github.com/MoePlayer/DPlayer/issues/501#issuecomment-507496622) 非常感谢

**Comment by kn007** [comment]
好的，那麻烦你关闭下issue

**Comment by axetroy** [comment]
请问楼上的解决了吗?

调用 `destroy()` 之后，依旧疯狂请求

**Comment by kn007** [comment]
@axetroy 你编译了么？
我提交了commit，但是只是源码改了，并没有输出编译好的文件。
编译办法你可以参照文档。
你也可以先下载上面的test501.zip先用着。

**Comment by axetroy** [comment]
@kn007 
非常感谢🙏

就是这个 BUG 已经修改了，只是还没有发布新版本吗？

需要的话，只能自己先编译？

**Comment by kn007** [comment]
是的，不好意思了。之前提交PR的时候，忘记了。。。（也是怕影响其他未提交的commit内容）

**Comment by guodalin** [comment]
请问什么时候可以提交新版本

**Comment by qingwufong** [comment]
1.29 发现也有这个问题：播放器销毁后，hls实例并没有销毁，一直刷ts。注意player销毁的时候hls实例也要销毁。
![截图](https://user-images.githubusercontent.com/6860888/186873920-65dde9a6-f8ad-476f-9b09-611aea749fc0.png)
底层hls播放相关的，都要小心这个问题，容易引发内存泄漏，需要代码手动销毁。
示例：
1. 创建播放器时，存下hls实例：
`       this.hls = new Hls();
        const hls = this.hls
        this.player = new DPlayer({
          container: playDom,
          video: {
            url: videoSource,
            type: "customHls",
            customType: {
              customHls: function (video, player) {
                hls.loadSource(video.src);
                hls.attachMedia(video);
              },
            },
          },
          hotkey: true,
          autoplay: true,
          live: true,
        });`
2. 在某个时机，比如页面组件销毁前手动销毁hls和播放器：
`  if (this.hls) {
      // 先销毁hls实例！不然会内存泄漏
      this.hls.stopLoad()
      this.hls.destroy()
      this.hls = null
    }
    this.player.destroy();
`
