### ISSUE TITLE
怎么修改DPlayer的视频缓冲时间？

### ISSUE THREAD

**Issue by 570295535** [MoePlayer/DPlayer#509]
如图，每次视频只能缓冲30秒，怎样设置可以直接缓冲完整个视频？
![snipaste_20190705_205024](https://user-images.githubusercontent.com/13345269/60723715-fce72c80-9f66-11e9-94f8-99812b297817.jpg)

**Comment by gzlock** [comment]
浏览器原生支持的视频格式，无法控制缓冲的长度
hls.js和dash.js都有对应的设置
