### ISSUE TITLE
全屏

### ISSUE THREAD

**Issue by Littleor** [MoePlayer/DPlayer#511]
在vue中使用dplayer
发现点击全屏有效
但是并不是横屏全屏
电脑上正常

**Comment by kn007** [comment]
你意思移动端不行是吧？
移动端的全屏受限于系统，只有系统内置播放器才能全屏自动横屏

**Comment by fuguiguan** [comment]
> 你意思移动端不行是吧？
> 移动端的全屏受限于系统，只有系统内置播放器才能全屏自动横屏

safari和ie浏览器的pc端全频后操作栏控件（播放、暂停、进度）样式错乱
