### ISSUE TITLE
可以发布一款支持uniapp的插件吗

### ISSUE THREAD

**Issue by ancientry** [MoePlayer/DPlayer#516]
可以发布一款支持uniapp的插件吗？？dplayer什么功能都很齐全，但是在uniapp没有，希望作者可以加一个uniapp的这个插件，这么好的东西，期待他的uniapp版本

**Comment by szBox** [comment]
你好，目前这个有解吗？ 我引入dplayer到uni-app, dplayer报错了
sdk uncaught third Error 
 setImmediate is not defined

**Comment by hnsylitao** [comment]
uni-app 不是跨端小程序的么，在小程序中对于媒体操作的api 都不同了

**Comment by hnsylitao** [comment]
当然，如果你只需要实现uni-h5 中的应用，应该是可以无缝切换使用的~
https://uniapp.dcloud.io/component/video

**Comment by szBox** [comment]
uni-app自带的video是原生应用级的，无法套在swiper中应用

<video/> 组件在非H5端是原生组件，层级高于普通前端组件，覆盖其需要使用cover-view组件或plus.nativeObj.view、subNVue。微信基础库 2.4.0 起已支持 video 组件的同层渲染，也就是video在非全屏时，可以被前端元素通过调节zindex来遮挡，但video全屏时，仍需要cover-view覆盖。

**Comment by szBox** [comment]
目前 我这里有个业务需求就是仿抖音那种  swiper 套个video，目前找到了dplayer，可是不兼容uni-app

**Comment by hnsylitao** [comment]
可能，我描述的有点不清楚，
uni-api 在多端实现 video 中，多端的api 是各不相同的，需要遵守顶层api实现。
所以如果你的业务是在 小程序端的，那这个是不合适的。
如果你的业务是在 HTML5来实现的 uni-app 也有说明能够支持一般的video js

**Comment by szBox** [comment]
能加下你的QQ 或者 微信吗？ 这里交流有点麻烦
