### ISSUE TITLE
It stops or playes not fluentlty when it has loaded the data of next minutes.

### ISSUE THREAD

**Issue by Zxq0900** [MoePlayer/DPlayer#518]
It stops or playes not fluentlty when it has loaded the data of next minutes.(As the title say)
What's more, it sometimes can't play and says it fail to analysis data.
![image](https://user-images.githubusercontent.com/43139129/61578843-81bd7300-ab2f-11e9-886f-913b49c1c1e8.png)

**Comment by DIYgod** [comment]
Can't reproduce it, please provide a minimal demo for the problem
