### ISSUE TITLE
视频能够播放,但是一快进或后退,就会重新播放.(而且播放不了本地视频,不过这没关系)

### ISSUE THREAD

**Issue by 904670145** [MoePlayer/DPlayer#519]
<template>
  <d-player id="videoElement" style="width:70%" ref="player" :options="options" @play="BeforePlayCallBack"></d-player>
</template>

<script type="text/ecmascript-6">
    import dPlayer from 'vue-dplayer'

    export default {
        components: {
            dPlayer
        },
        data () {
            return {
                player: null,
                options:{
                    video: {
                        url: this.rootUrl+"/api/fileUpload/download?name=无间道BD国粤双语中字.电影天堂.www.dy2018.com.mkv",
                        // url:"../iQOOTVC.mp4"
                        // url: 'D:\谷歌下载\yld2p-ueefn.avi'
                    },
                    autoplay:false,
                },
                contextmenu:[{}],

            }
        },
        mounted() {
            this.player = this.$refs.player.dp;
        },
        methods: {
            BeforePlayCallBack(){
                console.log("play callback+");
            },

        },
     
    }
</script>

Video can play, but it will play back as soon as it is fast forward or backward, and it doesn't seem to work for video in this project

**Comment by michaelfyc** [comment]
I encountered the same problem. Everytime I click on the progress bar trying to fast-forward or rewind, the video replays from the very beginning. I've set attribute 'hotkey' true, but did nothing.

**Comment by Copay** [comment]
@michaelfyc It should be your video server's problem.
The metadata about the video fast forward is provided by the video file server.

**Comment by michaelfyc** [comment]
@Copay Thank you for your reply. What's interesting is that the problem seems to occur solely on Chrome, while Firefox, Edge, and even IE work rather properly. I guess I'll have to add extra things to headers?

**Comment by suwu150** [comment]
如何播放本地视频
