### ISSUE TITLE
我的字幕不能显示

### ISSUE THREAD

**Issue by mingtian2250** [MoePlayer/DPlayer#524]
我遇到了一个问题，字幕的url如果是我直接设置好的，在播放视频的时候能显示字幕，但是经过某个api获取到字幕url后，再重新配置字幕url的值，播放器就不能显示字幕了

//能显示字幕
subtitle.url=xxx.vtt
//不能显示字幕
subtitle_url=http.get(http://xxxx.vtt)
subtitle.url = this.subtitle_url

**Comment by Copay** [comment]
@mingtian2250 请您确认您的http.get不是异步操作
