### ISSUE TITLE
请问可以控制进度条不让拖动吗？

### ISSUE THREAD

**Issue by prprpr** [MoePlayer/DPlayer#526]
请问可以控制进度条不让拖动吗？

**Comment by A-Circle-Zhang** [comment]
需要二次开发，修改控制栏部分的代码

**Comment by Copay** [comment]
@A-Circle-Zhang 可以直接用css取消掉可操作性

**Comment by Copay** [comment]
@A-Circle-Zhang https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
