### ISSUE TITLE
怎样支持H.265的视频

### ISSUE THREAD

**Issue by xiaosiqi111** [MoePlayer/DPlayer#530]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by Copay** [comment]
@xiaosiqi111 update your browser to a version that supports h.265

**Comment by sakuramisaki** [comment]
> @xiaosiqi111 update your browser to a version that supports h.265

My browser is chrome 76.0.3809.132 stable, I am using dplayer v1.25.0. When I try to play the hevc_10bit video, the interface is black, but the sound is normal. This does not happen when playing other encoded videos (such as h.264). At the same time, this is not a problem with the device. I can use the potplayer on the Microsoft surface to decode the hevc encoded video normally.

**Comment by TinkoLiu** [comment]
@sakuramisaki Browsers that supports H.265 see https://caniuse.com/#search=h265

**Comment by sakuramisaki** [comment]
> @sakuramisaki Browsers that supports H.265 see https://caniuse.com/#search=h265
> 
> Obviously, even you get Chrome to 79 you still can't play H.265 video.

![下载 _3_.jpg](https://i.loli.net/2019/09/04/Hh1RGxJmsvk5O8L.jpg)
Thank you.困扰我大半个月的问题终于解决了！
解决方法是:
首先到微软商店下载HEVC视频扩展，然后换用Edge浏览器就搞定了！♬(ノ゜∇゜)ノ♩
开心！o(≧v≦)o
能愉快地在自己的网盘上播放HEVC视频啦！
