### ISSUE TITLE
你好，手机端视频没有全屏选项吗？

### ISSUE THREAD

**Issue by act2009** [MoePlayer/DPlayer#534]
微信里访问页面就是视频无法全屏播放，播放器按钮也无效

**Comment by gzlock** [comment]
手机端的各种浏览器都有可能挟持html里的video标签，改为各自实现的video view
据我所知，微信，uc，夸克这类都有这个行为
安卓方面原生的chrome会靠谱一点

**Comment by act2009** [comment]
> �手机端的各种浏览器都有可能挟持html里的video标签，改为各自实现的video view
> 据我所知，微信，uc，夸克这类都有这个行为
> 安卓方面原生的chrome会靠谱一点
> 算有解答到吗？就是在手机app端里的网页不太可控

谢谢解答，这两天测试 有时候微信访问网页能看（显示会有小窗播放，全屏），有时候不能看（原样式，不能点击），有点懵，不知道如何设置让他默认可以全屏播放==

**Comment by act2009** [comment]
上个图

![image](https://user-images.githubusercontent.com/48006419/63843391-eb476180-c9b8-11e9-829b-45d979f988f2.png)

![image](https://user-images.githubusercontent.com/48006419/63843319-c9e67580-c9b8-11e9-877e-cd801cd81205.png)

**Comment by act2009** [comment]
第一种样式手机不能点击全屏是我自己的问题，我使用bootstrap，然后在代码里错误的加入了 col-xs-12类，导致dplayer在手机端不能全屏 ，记录一下吧
<div class="col-sm-8 col-xs-12">
   <div id="dplayer" ></div>
</div>

<div class="col-sm-4">
 
</div>
