### ISSUE TITLE
看视频见过卡的。没见过这么卡的。3秒1卡。10秒1卡。你这是存心不让人看电影啊。洗洗睡了吧。

### ISSUE THREAD

**Issue by 88866888** [MoePlayer/DPlayer#538]
看视频见过卡的。没见过这么卡的。3秒1卡。10秒1卡。你这是存心不让人看电影啊。洗洗睡了吧。

**Comment by xb2016** [comment]
@88866888 你充个一百万会有那么多批事？

**Comment by Copay** [comment]
@88866888 您好，我们并不提供托管服务。
请联系服务方而不是我们。
您的问题与项目无关。

**Comment by 88866888** [comment]
你们的只有原码没有客户端吧。
________________________________
发件人: De. Clare <notifications@github.com>
发送时间: 2019年8月30日 23:04
收件人: MoePlayer/DPlayer <DPlayer@noreply.github.com>
抄送: wuyongjun <wuyongjun@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [MoePlayer/DPlayer] 看视频见过卡的。没见过这么卡的。3秒1卡。10秒1卡。你这是存心不让人看电影啊。洗洗睡了吧。 (#538)


@88866888<https://github.com/88866888> 您好，我们并不提供托管服务。
请联系服务方而不是我们。
您的问题与项目无关。

―

**Comment by Copay** [comment]
@88866888 dplayer是一个开源前端视频播放器项目，不提供客户端支持。

**Comment by kn007** [comment]
说话讲证据，你看源码，哪里卡住你了。服务商不行还是自己网速不行，别怪到播放器上。

**Comment by Chriser001** [comment]
这只是一个播放器，仅仅为呈现视频播放，你看的网站视频源卡的问题与播放器无关，是你看的视频网站的问题。顺带，看正版就不会有这些事了，不要什么都怪播放器。
