### ISSUE TITLE
safri浏览器 进度条拖动有误差，不能点击或者拖到鼠标所在位置。

### ISSUE THREAD

**Issue by weibsgz** [MoePlayer/DPlayer#539]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
无法复现，看下是不是网站问题，CSS限定问题。

**Comment by DIYgod** [comment]
Can't reproduce it.

**Comment by MaZhaolin** [comment]
遇到了同样的问题，这个问题出现在mac端的Safari下面，移动端正常
