### ISSUE TITLE
如何加密视频地址？How to Encrypt Video Play URL？

### ISSUE THREAD

**Issue by BuTingBa** [MoePlayer/DPlayer#540]
怎么样才能把MP4地址加密播放啊？
How to Encrypt Video Play URL？

**Comment by kn007** [comment]
你播放时总要解密的。无意义啊。

**Comment by BuTingBa** [comment]
> 你播放时总要解密的。无意义啊。

就像优酷、腾讯等那种加密播放.....

**Comment by kn007** [comment]
那叫加密么。。。。你了解下hls
