### ISSUE TITLE
谷歌在新窗口打开不能自动播放视频  chrome can not autoplay in a new window 

### ISSUE THREAD

**Issue by weibsgz** [MoePlayer/DPlayer#543]
只能设置成静音才能自动播放
但是如果 在loadedmetadata方法中通过_this.dp.volume(1, true, true);设置成有声音的，视频就马上暂停了 
查了下是谷歌策略的问题，会报`Uncaught (in promise) DOMException`
但是我确实是i需要自动播放视频的，请问怎么解决

**Comment by kn007** [comment]
多播放几次。这个问题只能不用Chrome，或多播放几次，让浏览器知道你要自动播放

**Comment by hnsylitao** [comment]
你也说了，这是chrome 策略的问题，我们尽量按照浏览器的策略来调整。

**Comment by weibsgz** [comment]
> 多播放几次。这个问题只能不用Chrome，或多播放几次，让浏览器知道你要自动播放
怎么让客户多播几次。。。

**Comment by DIYgod** [comment]
It's Chrome's restriction, we have noting to do
