### ISSUE TITLE
怎样取消自带的右键菜单显示条目

### ISSUE THREAD

**Issue by Erik5169** [MoePlayer/DPlayer#544]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

自定义的右键菜单中合并了播放器自带的菜单选项， 怎样把自带的选项去掉？
<img width="252" alt="屏幕快照 2019-09-16 下午12 08 13" src="https://user-images.githubusercontent.com/25293699/64934052-d739a600-d87a-11e9-8e8d-64d8305142df.png">

**Comment by SmallishJoker** [comment]
you can use in JS

document.querySelector("#dplayer").oncontextmenu =  () => {
        document.querySelector(".dplayer-menu").style.display = "none";
        document.querySelector(".dplayer-mask").style.display = "none";
        return false;
};
