### ISSUE TITLE
flv.js 播放器返回问题

### ISSUE THREAD

**Issue by Erik5169** [MoePlayer/DPlayer#545]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

项目中引入flv.js 来做直播， 通过按钮进入到播放页面， 但是返回的时候， 调试器中不断的输出报错信息， 返回的时候 销毁的钩子函数也执行了  hls.js文件播放视频没有这个问题
<img width="572" alt="屏幕快照 2019-09-16 下午3 41 33" src="https://user-images.githubusercontent.com/25293699/64941740-01e72700-d89a-11e9-9e94-6ee1f0fbd819.png">
这个报错信息会持续输出

**Comment by Erik5169** [comment]
贴一下我的代码， 我的工程是Vue版本的，用的是nuxt框架， 经过测试， 发现是 this.player.destroy()
引起的， 目前只能把创建player修改为局部变量， 不能放在vue的data函数中引用， 局部变量的话，就不会用到destroy()这个函数了， 也不会有这个问题了

<template>
  <div ref="dplayer" class="dplayer-container" />
</template>

<script>
import 'dplayer/dist/DPlayer.min.css'
export default {
  name: 'MFPlayer',
  components: {},
  props: {
    model: {
      type: String,
      default: 'flv-only' // flv-hls:优先使用flv 模式， flv不兼容， 使用hls播放  flv-only: 只使用flv进行播放， hls-only: 只使用hls播放
    },
    flvUrl: {
      type: String,
      default: ''
    },
    hlsUrl: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      player: null,
      video: {
        url: this.flvUrl,
        type: 'flv'
      }
    }
  },
  computed: {},
  mounted() {
    // 检查浏览器兼容
    this.checkBrowser()
    this.initPlayer()
  },
  beforeDestroy() {
    if (this.player) {
      // console.log('destroyed')
      this.player.pause()
      this.player.destroy()
      this.player = null
    }
  },
  methods: {
    // 检查浏览器兼容
    checkBrowser() {
      const flvjs = require('flv.js').default
      const hls = require('hls.js')
      if (this.model === 'flv-only') {
        if (flvjs.isSupported()) {
          this.video.url = this.flvUrl
          this.video.type = 'flv'
        } else {
          console.log('浏览器不支持flv播放')
        }
      } else if (this.model === 'hls-only') {
        if (hls.isSupported()) {
          this.video.url = this.hlsUrl
          this.video.type = 'hls'
        } else {
          console.log('浏览器不支持hls播放')
        }
      } else {
        // 判断兼容性
        if (flvjs.isSupported()) {
          this.video.url = this.flvUrl
          this.video.type = 'flv'
        } else if (hls.isSupported()) {
          this.video.url = this.hlsUrl
          this.video.type = 'hls'
        } else {
          console.log('浏览器不支持flv和hls播放，请下载最新版本浏览')
        }
      }
    },
    initPlayer() {
      const DPlayer = require('dplayer')
      this.player = new DPlayer({
        container: this.$refs.dplayer,
        live: true,
        danmaku: false,
        autoplay: true,
        video: this.video
      })
    }
  }
}
</script>

**Comment by Erik5169** [comment]
没人解决这个问题吗？

**Comment by DIYgod** [comment]
Can't reproduce it, please provide a minimal demo for the problem
