### ISSUE TITLE
我想要播放器保持16:9的长宽比例该如何实现 (How do I want the player to maintain a 16:9 length-to-width ratio)

### ISSUE THREAD

**Issue by ebitgeek** [MoePlayer/DPlayer#575]
如题，我该如何要播放器保持16:9的长宽比例，而不是手动指定长宽？

How do I want the player to maintain a 16:9 length-to-width ratio

**Comment by gzlock** [comment]
@ebitgeek video网页元素有videoWidth和videoHeight属性，可以通过这两个属性计算长宽比例，再自己设置player的尺寸
