### ISSUE TITLE
npm包距离dplayer@1.25.0发布已经1年多了，求发个新版本把一些merge request的东西更新上来

### ISSUE THREAD

**Issue by lfyfly** [MoePlayer/DPlayer#587]
距离dplayer@1.25.0发布已经1年多了，求发个新版本把一些merge request的东西更新上来

**Comment by kn007** [comment]
已经更新过了啊，只不过版本号没变。

**Comment by lfyfly** [comment]
> 已经更新过了啊，只不过版本号没变。
npm 包没有更新啊

**Comment by wangxingkang** [comment]
+1

**Comment by wangxingkang** [comment]
有没有发布计划，要不然就得自己发个npm包 主要没啥意义

**Comment by wangxingkang** [comment]
@kn007

**Comment by kn007** [comment]
哦，release貌似没更新。回头吧

**Comment by wangxingkang** [comment]
![image](https://user-images.githubusercontent.com/14227679/66736467-d147dc80-ee9b-11e9-97e2-12b0655f0ac2.png)
是没有发布 npm

**Comment by kn007** [comment]
。。。。你不用老是at，看得到。
你每发一条信息都会给watcher带来提醒

**Comment by wangxingkang** [comment]
嗯嗯，不好意思

**Comment by wangxingkang** [comment]
大概什么时间会发布一个新的npm版本

**Comment by tongshs** [comment]
yarn add https://github.com/MoePlayer/DPlayer.git

**Comment by trtrtr6** [comment]
是啊，啥时候能能更新下版本啊，有些bug实在是影响有点大，比如移动版本进度条拖动问题，我看了最新代码有修改，但是没发新版本，跪求
