### ISSUE TITLE
统计视频时长问题

### ISSUE THREAD

**Issue by act2009** [MoePlayer/DPlayer#596]
...
const dp = new DPlayer({
container: document.getElementById('dplayer'),
autoplay: true,
theme: '#FADFA3',
loop: false,
lang: 'zh-cn',
screenshot: false,
hotkey: true,
volume: 0.7,
mutex: true,
video: {
    url: first_url,
     pic: cover,
    // thumbnails: '',
    type: 'auto'
},

});

console.log(dp.video.duration);

打印出来的结果为什么是NaN 属性?。。。哪里有错误吗？
![image](https://user-images.githubusercontent.com/48006419/66894980-58c05780-f024-11e9-8ebe-0805266df9ca.png)

而打印dp.video结果是下面这样：
console.log(dp.video);

![image](https://user-images.githubusercontent.com/48006419/66895105-945b2180-f024-11e9-8b86-b9f0c102e030.png)

**Comment by xincmm** [comment]
根据：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video 中的介绍。
`duration`
一个双精度浮点值，它指示媒体的持续时间(总长度)，以秒为单位，在媒体的时间线上。**如果元素上没有媒体，或者媒体无效，则返回的值为NaN**。如果媒体没有已知终点(例如时间未知的实时流、网络广播、来自WebRTC的媒体等等)，那么这个值就是Infinity。

**Comment by act2009** [comment]
> 根据：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video 中的介绍。
> `duration`
> 一个双精度浮点值，它指示媒体的持续时间(总长度)，以秒为单位，在媒体的时间线上。**如果元素上没有媒体，或者媒体无效，则返回的值为NaN**。如果媒体没有已知终点(例如时间未知的实时流、网络广播、来自WebRTC的媒体等等)，那么这个值就是Infinity。

好的 谢谢~
