### ISSUE TITLE
直播状态下，视频怎样重新加载

### ISSUE THREAD

**Issue by Erik5169** [MoePlayer/DPlayer#605]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

直播状态下，点击暂停一段时间后， 然后点击播放，怎样重新加载最新的直播视频资源， 而不是从暂停的位置播放

**Comment by amhoho** [comment]
ios下目前还是有这个问题
