### ISSUE TITLE
如何添加一个播放按钮到屏幕中央？？？

### ISSUE THREAD

**Issue by wang5561207** [MoePlayer/DPlayer#607]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by steveLzsLR** [comment]
在播放器上面加一个浮层，浮层上添加播放按钮，在这个播放按钮上添加点击事件，调用dplayer实例的toggle()方法，关键代码如下：
> HTML部分
```HTML
<div class="m">
         <div class="videoWapper" id="videoWapper">
                    <div id="videoPlayers" class="dplayer" style="width:100%;height:100%;display: none;"></div>
         </div>
         <div class="playMask" id="playMask">
             <img src="../../images/playicon.png">
         </div>
</div>
```
> JAVASCRIPT部分
```JAVASCRIPT
        //播放按钮遮罩层
        var playMask = document.getElementById("playMask");
        playMask.style.display = "block";
        //== dplayer
        videoPlayers = new DPlayer({
            container: document.getElementById('videoPlayers'),
            preload: 'auto',
            autoplay: false,
            live: true,
            screenshot: false,
            mutex: false,
            volume: 0.9,
            video: {
                url: liveDetail.hlsUrl,
                type: 'hls',
            }
        });

        videoPlayers.on('error', function() {
            Log("播放器发生错误");
        });
        videoPlayers.on('canplay', function() {
            Log("播放器canplay");

        });
        videoPlayers.on('canplaythrough', function() {
            Log("播放器canplay");

        });
        videoPlayers.on('ended', function() {
            Log("播放器播放结束");
        });
        videoPlayers.on('fullscreen', function() {
            Log("播放器全屏事件");
        });
        //遮罩层点击事件绑定
        playMask.addEventListener("tap", function() {
            playMask.style.display = "none";
            videoPlayers.toggle();
        });
```

**Comment by 2757227663** [comment]
> 在播放器上面加一个浮层，浮层上添加播放按钮，在这个播放按钮上添加点击事件，调用dplayer实例的toggle()方法，关键代码如下：
> 
> > HTML部分
> 
> ```
> <div class="m">
>          <div class="videoWapper" id="videoWapper">
>                     <div id="videoPlayers" class="dplayer" style="width:100%;height:100%;display: none;"></div>
>          </div>
>          <div class="playMask" id="playMask">
>              <img src="../../images/playicon.png">
>          </div>
> </div>
> ```
> 
> > JAVASCRIPT部分
> 
> ```js
>         //播放按钮遮罩层
>         var playMask = document.getElementById("playMask");
>         playMask.style.display = "block";
>         //== dplayer
>         videoPlayers = new DPlayer({
>             container: document.getElementById('videoPlayers'),
>             preload: 'auto',
>             autoplay: false,
>             live: true,
>             screenshot: false,
>             mutex: false,
>             volume: 0.9,
>             video: {
>                 url: liveDetail.hlsUrl,
>                 type: 'hls',
>             }
>         });
> 
>         videoPlayers.on('error', function() {
>             Log("播放器发生错误");
>         });
>         videoPlayers.on('canplay', function() {
>             Log("播放器canplay");
> 
>         });
>         videoPlayers.on('canplaythrough', function() {
>             Log("播放器canplay");
> 
>         });
>         videoPlayers.on('ended', function() {
>             Log("播放器播放结束");
>         });
>         videoPlayers.on('fullscreen', function() {
>             Log("播放器全屏事件");
>         });
>         //遮罩层点击事件绑定
>         playMask.addEventListener("tap", function() {
>             playMask.style.display = "none";
>             videoPlayers.toggle();
>         });
> ```

能给个视频教程吗。小白看不懂
