### ISSUE TITLE
在移动设备上全屏后，无法显示字幕

### ISSUE THREAD

**Issue by limeng4835652** [MoePlayer/DPlayer#611]
在移动设备上全屏后无法显示字幕。

**Comment by Copay** [comment]
@limeng4835652 Make sure the player isn't replaced by system's one.

**Comment by Copay** [comment]
@limeng4835652 Suggestion: Provide your system info and browser info.

**Comment by limeng4835652** [comment]
system: iOS 13.1.2
browser: Safari
