### ISSUE TITLE
Question: Use <video> tag instead parent-<div>

### ISSUE THREAD

**Issue by doublex** [MoePlayer/DPlayer#613]
We have a `<video>`-tag, e.g.: `<video id="player"><source...></video>`.
Is there a chance to create a DPlayer-Instance using this `<video>`-tag?

**Comment by chenlin1994** [comment]
yes you can，but the source is unuseful




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"doublex"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 晚上9:18
收件人:&nbsp;"MoePlayer/DPlayer"<DPlayer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MoePlayer/DPlayer] Question: Use <video&gt; tag instead parent-<div&gt; (#613)




We have a <video&gt;-tag, e.g.: <video id="player"&gt;<source...&gt;</video&gt;.
 Is there a chance to create a DPlayer-Instance using this <video&gt;-tag?
