### ISSUE TITLE
播放HEVC的视频黑屏有声音是怎么回事？

### ISSUE THREAD

**Issue by zhao0742** [MoePlayer/DPlayer#623]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by lmali** [comment]
機器不支援H265的播放?

**Comment by zhao0742** [comment]
您是说我电脑？？我电脑可以的啊

**Comment by zhao0742** [comment]
> 机器不支持H265的播放？

您是说我电脑么？我电脑可以播放的啊！

**Comment by shafishcn** [comment]
感觉好无脑，怎么办。当你提issues的时候，先在项目的issus搜索框里看看有没有类似问题，这是基本操作吧。（这是一条吐槽，无意冒犯，如有不适，就不适吧）
![fish](https://user-images.githubusercontent.com/22794651/68364970-6623ba00-016a-11ea-935d-22355ef9bc31.png)

**Comment by zhao0742** [comment]
> 感觉好无脑，怎么办。当你提issues的时候，先在项目的issus搜索框里看看有没有类似问题，这是基本操作吧。（这是一条吐槽，无意冒犯，如有不适，就不适吧）
> ![fish](https://user-images.githubusercontent.com/22794651/68364970-6623ba00-016a-11ea-935d-22355ef9bc31.png)

对不住啊 我刚注册号 不懂这里的的用法 搜索了下 明白了怎么回事  虽然你说话恶毒  但是我还是要谢谢你 毕竟的我问题解决了

**Comment by shafishcn** [comment]
> > 感觉好无脑，怎么办。当你提issues的时候，先在项目的issus搜索框里看看有没有类似问题，这是基本操作吧。（这是一条吐槽，无意冒犯，如有不适，就不适吧）
> > ![fish](https://user-images.githubusercontent.com/22794651/68364970-6623ba00-016a-11ea-935d-22355ef9bc31.png)
> 
> 对不住啊 我刚注册号 不懂这里的的用法 搜索了下 明白了怎么回事 虽然你说话恶毒 但是我还是要谢谢你 毕竟的我问题解决了

如果还有疑问欢迎再来哟，亲(๑•̀ㅂ•́)و✧
