### ISSUE TITLE
How do I play my live stream (pull stream), Which configuration do I need to play it, for example rtmp://localhost:port/oflaDemo

### ISSUE THREAD

**Issue by yaotengyuan** [MoePlayer/DPlayer#629]
How do I play my live stream (pull stream), Which configuration do I need to play it, for example rtmp://localhost:port/oflaDemo

**Comment by yaotengyuan** [comment]
Also I have a stream name，how to config it that makes me confused, please someone tell me,thank you!

**Comment by yaotengyuan** [comment]
我怎么播放我的直播流（拉流），需要怎么配置呢，例如rtmp://localhost:port/oflaDemo

**Comment by wangxingkang** [comment]
rtmp is not supported
