### ISSUE TITLE
rtmp is not supported

### ISSUE THREAD

**Issue by yaotengyuan** [MoePlayer/DPlayer#630]
rtmp is not supported

_Originally posted by @wangxingkang in https://github.com/MoePlayer/DPlayer/issues/629#issuecomment-551407674_

thank you，by the way , what kind of protocol of live stream is the dplay support?

**Comment by Copay** [comment]
@yaotengyuan hls

**Comment by wangxingkang** [comment]
Need to use flash, you see [videojs-flash](https://github.com/videojs/videojs-flash)

**Comment by yaotengyuan** [comment]
thanks
