### ISSUE TITLE
Chrome for Android get Error when danmaku api crash

### ISSUE THREAD

**Issue by journey-ad** [MoePlayer/DPlayer#68]
OS: Android 5.0.2
Browser: Chrome Dev 60.0.3087.3
[demo](https://url.imjad.cn/dperr)

![Screenshot_2017-05-04-10-30-49.png](https://img.imjad.cn/images/2017/05/04/Screenshot_2017-05-04-10-30-49.png)

**Comment by journey-ad** [comment]
Maybe it is Chrome Dev 60.0.3087.3 's Bug

**Comment by zytx121** [comment]
find a jad酱！！

did you considerate  add  danmaku  function for imjad api  ?  i'm very  looking forward to it!!

hope DIYgod  don't mind - -!

**Comment by zytx121** [comment]
ps. redmi 4x chrome 58.0.3029  also have this problem in your demo
