### ISSUE TITLE
DPlayer-thumbnails-master是否可以以插件形式，网络加载播放视频是否可以自动生成预览图呢？

### ISSUE THREAD

**Issue by 721806280** [MoePlayer/DPlayer#687]

**Comment by 721806280** [comment]
手动或者使用批处理是可以生成缩图，但是需要保存图片还需要存储以及关联数据库，有没有什么办法去掉这一过程，网络加载截取视频缩图这样？

**Comment by zhw2590582** [comment]
可以实现，不过这样的话就得把视频完整加载一遍才行，不太合理

**Comment by 721806280** [comment]
对，性能上来说是这样，业余请教：像爱奇艺等这样的在线播放器，也采用的是这种截图存储的方式吗？

**Comment by zhw2590582** [comment]
直接前端生成缩略图的方法就是用canvas，但这就有问题，例如你看到第一秒，但视频已经加载到第五秒，你要第五秒的缩略图就得把视频快进到第五秒才行。要么另外再开一个视频请求专门用来生成缩略图，互不相关，不合理就在这，你打开页面还得加载两个同样的视频。所有网站的缩略图都是存储起来的。

**Comment by Super12138** [comment]
如何使用DPlayer-thumbnails？
