### ISSUE TITLE
请问怎么设置禁止迅雷下载  How to ban Thunder Download

### ISSUE THREAD

**Issue by wqssf** [MoePlayer/DPlayer#691]
我在使用dplayer的过程中，发现迅雷软件可以在当前网页页面下载视频，请问该如何禁止用户对视频的下载呢？
In the process of using dplayer, I found that Thunder software can download videos on the current web page. How can I prevent users from downloading videos?
![Uploading 123456.png…]()

**Comment by TinkoLiu** [comment]
这个是你服务端设置的东西，跟dplayer无关

**Comment by wqssf** [comment]
收到，非常感谢您的解答。感谢您们开发出这么好用的播放器。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tinko"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 晚上10:59
收件人:&nbsp;"MoePlayer/DPlayer"<DPlayer@noreply.github.com&gt;;
抄送:&nbsp;"Jonson"<565715597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MoePlayer/DPlayer] 请问怎么设置禁止迅雷下载  How to ban Thunder Download (#691)




这个是你服务端设置的东西，跟dplayer无关

**Comment by a807966224** [comment]
你好，没有理解你的意思，这个迅雷下载应该和视频没有关系，具体怎么设置禁止下载呢，帮忙指导下，辛苦
