### ISSUE TITLE
PC端浏览器小窗口模式样式丢失

### ISSUE THREAD

**Issue by xwlcn** [MoePlayer/DPlayer#699]
PC端浏览器小窗口模式样式丢失，变成了原始的`video`控制条，测试了优酷、斗鱼H5播放器小窗口模式都没有此问题，所以小窗口模式应该是可以做到样式不丢失的。

**Comment by Copay** [comment]
@xwlcn 请问“小窗口模式”是指代什么？

**Comment by xwlcn** [comment]
@Copay 比如我用的360浏览器，在播放器未全屏状态下鼠标移动到播放器上时，播放器的右上角就会出现“小窗口播放”的按钮，点击后就是小窗口模式（就是整个窗口就剩个播放器，其他网页元素全部隐藏了）。
