### ISSUE TITLE
搭配flv.js销毁播放器后也会一直缓冲视频

### ISSUE THREAD

**Issue by Pearlulu** [MoePlayer/DPlayer#724]
搭配flv.js播放flv视频，dp.destroy()销毁播放器后，flv.min.js会继续缓冲整个视频，并不会停下来，控制台里能看到flv.min.js一直报错。

**Comment by kn007** [comment]
用最新源码，自己编译。

**Comment by Pearlulu** [comment]
> 用最新源码，自己编译。

用customType新建播放器，销毁的时候多加个flvPlayer.destroy()也能解决，就是麻烦了点

**Comment by Pearlulu** [comment]
我去编译下新的
