### ISSUE TITLE
不支持播放X265 10bit的mkv视频视频

### ISSUE THREAD

**Issue by sunnyhu2003** [MoePlayer/DPlayer#729]
会报错'视频加载失败'。但是使用第三方播放器如potplayer键入视频源链接可以正常播放，所以源无问题。同时Dplayer播放其他相同源的视频也没有问题，唯独不兼容（目前发现的）x265 10bit的mkv视频dplayer版本1.250，求大佬适配

**Comment by TinkoLiu** [comment]
https://caniuse.com/#search=hevc
浏览器对HEVC视频的支持范围
你可以选一个支持的浏览器就能放了
跟DPlayer没关系

**Comment by sunnyhu2003** [comment]
> https://caniuse.com/#search=hevc
> 浏览器对HEVC视频的支持范围
> 你可以选一个支持的浏览器就能放了
> 跟DPlayer没关系
> 以及发issue之前不先自己搜一搜吗#530

sorry,没想那么多，下次会注意了

**Comment by sunnyhu2003** [comment]
> https://caniuse.com/#search=hevc
> 浏览器对HEVC视频的支持范围
> 你可以选一个支持的浏览器就能放了
> 跟DPlayer没关系
> 以及发issue之前不先自己搜一搜吗#530

根据这里：https://caniuse.com/#search=hevc
ios的内建浏览器也是支持hevc的，但是经过测试仍旧显示‘视频加载失败’
我下载了个第三方编译后支持hevc的chromium,仍旧显示‘视频加载失败’
也许真的是适配有问题

**Comment by Copay** [comment]
@sunnyhu2003 你试一下直接通过video元素加载，看看这些浏览器能不能放。

**Comment by sunnyhu2003** [comment]
> @sunnyhu2003 你试一下直接通过video元素加载，看看这些浏览器能不能放。

测试完了,safari是不支持的，但不知到为什么列表里会有它。反倒是QQ内置的浏览器支持，我人都傻了

**Comment by Copay** [comment]
@sunnyhu2003 如果不能放就是浏览器问题

**Comment by liyoubdu** [comment]
> > https://caniuse.com/#search=hevc
> > 浏览器对HEVC视频的支持范围
> > 你可以选一个支持的浏览器就能放了
> > 跟DPlayer没关系
> > 以及发issue之前不先自己搜一搜吗#530
> 
> 根据这里：https://caniuse.com/#search=hevc
> ios的内建浏览器也是支持hevc的，但是经过测试仍旧显示‘视频加载失败’
> 我下载了个第三方编译后支持hevc的chromium,仍旧显示‘视频加载失败’
> 也许真的是适配有问题

"下载了个第三方编译后支持hevc的chromium"， 有下载链接吗？我找不到一个支持hevc的chromium。
