### ISSUE TITLE
dplayer无法播放部分m3u8链接，同链接ckplayer可以播放，请求作者指点

### ISSUE THREAD

**Issue by 721806280** [MoePlayer/DPlayer#743]
测试地址：http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8

dplayer：不可用，代码如下（已加载hls.js和dplayer.js）：

const dp = new DPlayer({
        container: document.getElementById('dplayer'),
        autoplay: true,
        live: true,
        screenshot: true,
        video: {
            url: 'http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8',
            type: 'hls',
        }
    });

ckplayer：可以播放

**Comment by Copay** [comment]
@721806280 请给出demo page

**Comment by 721806280** [comment]
dplayer  demo

`<meta charset="UTF-8">
<link href="static/js/DPlayer/DPlayer.min.css" rel="stylesheet">
<style type="text/css">
    body, html {
        width: 100%;
        height: 100%;
        background: #000;
        padding: 0;
        margin: 0;
        overflow-x: hidden;
        overflow-y: hidden
    }

    * {
        margin: 0;
        border: 0;
        padding: 0;
        text-decoration: none
    }

    #stats {
        position: fixed;
        top: 5px;
        left: 10px;
        font-size: 12px;
        color: #fdfdfd;
        z-index: 2147483647;
        text-shadow: 1px 1px 1px #000, 1px 1px 1px #000
    }

    #dplayer {
        position: inherit
    }
</style>
<div id="dplayer"></div>
<div id="stats"></div>
<script src="https://cdn.jsdelivr.net/npm/cdnbye@latest"></script>
<script src="static/js/DPlayer/DPlayer.min.js"></script>
<script>
    var _peerId = '', _peerNum = 0, _totalP2PDownloaded = 0, _totalP2PUploaded = 0;
    var type = 'customHls';
    if (navigator.userAgent.match(/iPad|iPhone|iPod|Baidu|UCBrowser/i)) {
        type = 'normal';
    }
    const dp = new DPlayer({
        container: document.getElementById('dplayer'),
        autoplay: true,
        live: true,
        video: {
            url: "http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8",
            // url: 'https://1257070836.vod2.myqcloud.com/0cf6732evodtransgzp1257070836/81fe3a525285890782510564774/v.f220.m3u8',
            type: type,
            customType: {
                'customHls': function (video, player) {
                    const hls = new Hls({
                        debug: false,
                        // Other hlsjsConfig options provided by hls.js
                        p2pConfig: {
                            logLevel: false,
                            live: true,        // 如果是直播设为true
                            // Other p2pConfig options provided by CDNBye
                        }
                    });
                    hls.loadSource(video.src);
                    hls.attachMedia(video);
                    hls.p2pEngine.on('stats', function (stats) {
                        _totalP2PDownloaded = stats.totalP2PDownloaded;
                        _totalP2PUploaded = stats.totalP2PUploaded;
                        updateStats();
                    }).on('peerId', function (peerId) {
                        _peerId = peerId;
                    }).on('peers', function (peers) {
                        _peerNum = peers.length;
                        updateStats();
                    });
                }
            }
        }
    });

    function updateStats() {
        const text = 'P2P正在为您加速' + (_totalP2PDownloaded / 1024).toFixed(2)
            + 'MB 已分享' + (_totalP2PUploaded / 1024).toFixed(2) + 'MB' + ' 连接节点' + _peerNum + '个';
        document.getElementById('stats').innerText = text
    }
</script>
`

**Comment by 721806280** [comment]
ckplayer demo

`<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
    <title>ckplayer-m3u8</title>
    <style type="text/css">body, html, .a1 {
        background-color: #000;
        padding: 0;
        margin: 0;
        width: 100%;
        height: 100%;
    }</style>
    <script src="ckplayer/ckplayer.js" type="text/javascript"></script>
</head>
<body oncontextmenu="window.event.returnValue=false" ondragstart="window.event.returnValue=false"
      onselectstart="event.returnValue=false" style="overflow-y:hidden;">
<div id="video" style="width:100%;height:100%;"></div>
<script type="text/javascript">
    var videoObject = {
        container: '#video',
        variable: 'player',
        autoplay: true,
        live: true,
        video: 'http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8'
    };
    var player = new ckplayer(videoObject);
</script>
</body>
</html>
`

**Comment by 721806280** [comment]
加载dplayer的js和css

------<div id="dplayer"></div>----
const dp = new DPlayer({
container: document.getElementById('dplayer'),
autoplay: true,
live: true,
screenshot: true,
video: {
url: 'http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8',
type: 'hls',
}
});

**Comment by 721806280** [comment]
加载ckplayer的js和css

div id="ckplayer"

<script type="text/javascript">
    var videoObject = {
        container: '#video',
        variable: 'player',
        autoplay: true,
        live: true,
        video: 'http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8'
    };
    var player = new ckplayer(videoObject);
</script>

**Comment by Copay** [comment]
A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

please

**Comment by 721806280** [comment]
https://codepen.io/721806280/pen/KKpMbNd

**Comment by Copay** [comment]
是跨域请求问题，你连接的m3u8文件没有CORS头，或者只允许特定网站进行ajax请求。
详情参阅：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS
至于ckplayer可以播放是因为flash对于跨域请求没有限制，但是浏览器端对此非常严格。所以依赖ajax的hls.js无法获取m3u8文件。

**Comment by 721806280** [comment]
非常感谢您的解答，谢谢；

**Comment by MrTlyer** [comment]
>问一下有些M3U8格式的链接IOS手机端能播放，dplayer播不了是什么原因？
比如：http://source07.v.news.cn/live/CNC_CN/playlist.m3u8 @Copay
