### ISSUE TITLE
微信里播放器右上角会被添加“全屏”按钮，点击“全屏”按钮后，播放器的全屏功能失效

### ISSUE THREAD

**Issue by shihaha** [MoePlayer/DPlayer#751]
在微信内打开DPlayer页面，播放器窗口的右上角会被微信加上“全屏”按钮，不点击这个“全屏”按钮时，DPlayer自己的全屏按钮好使，当点击这个由微信添加的“全屏”按钮后，DPlayer自己的全屏按钮失效了

**Comment by amyhuangxbd** [comment]
我也遇到同样问题，请问怎么解决？

**Comment by weiwentao518** [comment]
+1 我也遇到了这个问题。求解决

**Comment by amyhuangxbd** [comment]
需要监听x5全屏事件
this.dp.video.addEventListener('x5videoexitfullscreen', this.x5ExitEventFunc, true)
