### ISSUE TITLE
你好，最新版电脑微信浏览器是不是把dplayer给屏蔽了，访问官网无法正常加载

### ISSUE THREAD

**Issue by act2009** [MoePlayer/DPlayer#767]
![image](https://user-images.githubusercontent.com/48006419/76374680-db083a00-637e-11ea-87ea-20c5e675ba1f.png)

而video.js的demo能够正常访问

![image](https://user-images.githubusercontent.com/48006419/76374969-9a5cf080-637f-11ea-8ee6-06ee5ed28afa.png)

**Comment by Copay** [comment]
@act2009 您好, 微信浏览器就是个残废

**Comment by act2009** [comment]
> @act2009 您好, 微信浏览器就是个残废

有一说一，确实，店大欺客，架不住客户喜欢用，唉，项目网站唯独就在这播放不了。。

**Comment by kn007** [comment]
https://kn007.net/topics/legends-never-die/

测试通过啊

![QQ截图20200311121455](https://user-images.githubusercontent.com/6196903/76381938-f2045780-6391-11ea-8f16-1f4dc5738eb9.png)

**Comment by act2009** [comment]
> https://kn007.net/topics/legends-never-die/
> 
> 测试通过啊
> 
> ![QQ截图20200311121455](https://user-images.githubusercontent.com/6196903/76381938-f2045780-6391-11ea-8f16-1f4dc5738eb9.png)
> 
> ![QQ截图20200311121532](https://user-images.githubusercontent.com/6196903/76381963-0a747200-6392-11ea-9957-652600061dbb.png)
> 
> ![QQ截图20200311121609](https://user-images.githubusercontent.com/6196903/76381987-1fe99c00-6392-11ea-924d-356b12a8efa2.png)
有没有什么特别的配置啊。。
奇怪，官网是不能加载的，你能打开dplayer官网看看吗？http://dplayer.js.org/

**Comment by kn007** [comment]
@act2009 确实不行，没什么特别的配置。我用的是DPlayer-Lite。
其实就是相当于DPlayer最新代码编译的，但是去掉一些功能。
