### ISSUE TITLE
请问怎么去掉“视频统计信息”？

### ISSUE THREAD

**Issue by yogian** [MoePlayer/DPlayer#768]
右键菜单里有个视频统计信息，会显示视频下载地址，我不想暴露视频下载地址，不知道有没有方法可以把这个视频统计信息去掉？

**Comment by Matrixbirds** [comment]
硬编码的默认值 fork仓库自己改吧

**Comment by fuguiguan** [comment]
我也是这样想的

**Comment by baobao12356** [comment]
.dplayer .dplayer-menu.dplayer-menu-show {
  display: none !important;
}
