### ISSUE TITLE
有办法支持mpeg-4格式的mp4吗？Anyway to play video in mpeg-4 format？

### ISSUE THREAD

**Issue by rtz43** [MoePlayer/DPlayer#782]
Dplayer可以播放mpeg-4的视频吗？部分H.264格式的mp4文件可以顺利播放，但mpeg4格式的视频无法播放，黑屏，但有声音。
Can Dplayer play video that encode with mpeg-4？I find that Dplayer can play video that encode with H.264,but can not play with mpeg-4.the screen is black but sound can be played.

**Comment by RexSkz** [comment]
I think it's beyond DPlayer's goal.

Browsers currently only support H.264 encoding (which is known as MPEG-4 part 10, not the whole MPEG-4), no matter what extension name your video uses.

For video not encoded in H.264, the only way to play it in browser is to use software decoding (such as WebAssembly). Considering the CPU cost and code complexity, maybe using server-side transcoding is a better way.
