### ISSUE TITLE
Demo "full screen" button fails in qq browser

### ISSUE THREAD

**Issue by 612-A-34** [MoePlayer/DPlayer#784]
Hello, thank you for providing such a good code, your demo in the QQ browser and 360 browser "full screen" button is disabled, "web page full screen" is available. In my project, the player has a fixed size, but there will be a mobile video (vertical screen) video playback (he will automatically adapt to 100% width, and the height of the player changes accordingly). In order not to change the style, the player height is fixed As a result, the "Web Full Screen" button cannot implement the full screen function. Google Chrome is available in "full screen", but 360 and QQ browsers cannot be full screen. My project URL: https://www.imifanlive.com

您好，感谢您提供这么好的代码，您的demo在QQ浏览器和360浏览器”全屏“按钮失效，”网页全屏“可用。我的项目中，播放器固定大小，但是会有手机视频（竖屏）视频播放（他会自动适应到100%宽度，播放器高度随之改变），为了不改变样式，固定了播放器高度，导致”网页全屏“按钮实现不了全屏功能。谷歌浏览器可用”全屏“，但是360和QQ浏览器就无法全屏。我的项目网址：https://www.imifanlive.com

**Comment by Copay** [comment]
@612-A-34 您好，之所以出现这样的事情，完全是这些无趣的QQ浏览器与360浏览器所自己遭致的。目前对于这类愚蠢的浏览器，并没有什么好的解决方案。
