### ISSUE TITLE
直播flv hls怎么添加弹幕功能？

### ISSUE THREAD

**Issue by 24021438** [MoePlayer/DPlayer#795]
请问大佬直播视频怎么添加弹幕功能？flv  hls

**Comment by chenlin1994** [comment]
dplayer是提供了的 如果是用flv或许hls的话就得自己封装------------------ 原始邮件 ------------------
发件人: "24021438"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 中午12:40
收件人: "MoePlayer/DPlayer"<DPlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [MoePlayer/DPlayer] 直播flv hls怎么添加弹幕功能？ (#795)




 
请问大佬直播视频怎么添加弹幕功能？flv  hls
 
&mdash;

**Comment by 24021438** [comment]
大佬指条路

**Comment by MonoLogueChi** [comment]
使用 `apiBackend` 参数配合 `dp.danmaku` 接口 ，可以参考文档 http://dplayer.js.org/zh/guide.html#直播
