### ISSUE TITLE
How to destory the player

### ISSUE THREAD

**Issue by F-loat** [MoePlayer/DPlayer#81]
really a nice player but I have some problem use dplayer v1.1.4 with vue-router.

When I open a play page use hotkey to play the video and back to home open the play page use hotkey to paly again even the page is `not keep-alive`, the last video's audio still exists. Use play button is no problem.

------------

我第二次打开播放页时，使用热键播放的话，之前播放的视频的音频依然会播放，也就是同时播放了两个音频，把播放页设置为 `not keep-alive`也不行，但是通过点击播放按钮来播放就没有这个问题

**Comment by kslr** [comment]
我碰到了同样的问题，你有什么眉目吗？我现在通过刷新页面来更新dom。

**Comment by DIYgod** [comment]
Done. https://github.com/MoePlayer/DPlayer/commit/1e21471519c5bdf93252d0e497fcbbce9f727c94
