### ISSUE TITLE
弹幕 挂了

### ISSUE THREAD

**Issue by handashuai** [MoePlayer/DPlayer#814]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by handashuai** [comment]
能不能 给个 开发文档，

弹幕格式 的  api 数据格式 

这样也能 自己做 弹幕 后台api

**Comment by chenlin1994** [comment]
人家api给的很清楚了呀&nbsp;实在不清楚可以去看看源码啊&nbsp;不要做伸手党




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"handashuai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 凌晨5:27
收件人:&nbsp;"MoePlayer/DPlayer"<DPlayer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [MoePlayer/DPlayer] 弹幕 挂了 (#814)





 
能不能 给个 开发文档，
 
弹幕格式 的  api 数据格式
 
这样也能 自己做 弹幕 后台api
