### ISSUE TITLE
Problem occur when using Pjax/播放器在Pjax刷新后消失

### ISSUE THREAD

**Issue by ojhdt** [MoePlayer/DPlayer#815]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

我使用的代码：
```
<head>
    <script src="https://cdn.jsdelivr.net/npm/dplayer@1.25.0/dist/DPlayer.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dplayer@1.25.0/dist/DPlayer.min.css">
</head>
<body>
...
<div id="dplayer-1"></div>
<script id="dplayer-script">
    const dp = new DPlayer({
        container: document.getElementById('dplayer-1'),
        video: {
            url: 'A.mp4',
            pic: 'B.png'
        },
    });
</script>
...
```
播放器在使用Pjax刷新后无法正常显示

**Comment by Copay** [comment]
@ojhdt Please make a minimal demo via codepen.io
