### ISSUE TITLE
new version (1.25.1) has no `dist/DPlayer.min.css` while it's in the doc

### ISSUE THREAD

**Issue by zhangciwu** [MoePlayer/DPlayer#816]
`import 'dplayer/dist/DPlayer.min.css';`
But `dist/DPlayer.min.css` is missing in version 1.25.1
I think it's a bug

**Comment by kn007** [comment]
内置css，是你代码问题。。

**Comment by zhangciwu** [comment]
https://github.com/MoePlayer/DPlayer/blame/master/docs/guide.md#L79

So this line is not needed?
