### ISSUE TITLE
Issue with synch with time of the video and comments (mostly in live)

### ISSUE THREAD

**Issue by stigm4** [MoePlayer/DPlayer#82]
There's an issue with times, for example, when you see an live, and it is on 5:00, when you post a comment in minute 5:00 and other people are in 4:30, they can actually see the comment, and can be a potentially spoiler for people

**Comment by DIYgod** [comment]
I have no solution for it, but I think websocket danmaku is a better way for live.

**Comment by RexSkz** [comment]
There's no "time" in live, I think all people should watch the same danmaku at the first time. Does there any live service have an exception?
