### ISSUE TITLE
请问如何解决跨域问题？

### ISSUE THREAD

**Issue by xhemj** [MoePlayer/DPlayer#832]
请问如何解决跨域问题？
from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by augustdai** [comment]
同问

**Comment by Pearlulu** [comment]
服务器端nginx加个允许跨域的header就行了

**Comment by xhemj** [comment]
> 服务器端nginx加个允许跨域的header就行了

我是把网部署在Github上的，请问一下改如何操作，谢谢

**Comment by Pearlulu** [comment]
要视频所在的后端服务器，添加发送Access-Control-Allow-Origin的header，和前端没关系。如果是别人网站的视频，那只能通过自己的服务器反代，不能随便跨域的。

**Comment by Dolov** [comment]
因为 video 标签上面设置了 crossorigin = "annoymous" 所以无法访问第三方资源，可以在dom 加载之后 js 动态设置 crossorigin = ”use-credentials“
