### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by xy14053156** [MoePlayer/DPlayer#838]
https://mobile.medmeeting.com里边用到了dplayer
出现一个bug，音量默认是70%，一旦调整音量大小，就静音，怎么点都不能出声音了。
win10 浏览器是360 chrome 9.0.1.162 dplayer是1.25.0

**Comment by kn007** [comment]
找你自己原因，或者不要用360
https://mobile.medmeeting.com/#/live/video/share/2170
测试以上地址，正常。

**Comment by kn007** [comment]
我拿360试了也正常。

**Comment by xy14053156** [comment]
你给的地址没有问题https://mobile.medmeeting.com/#/live/show/share/104273
这个使用360或者ms Edge都是点了几次静音以后，就再也打不开声音了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karl Chen"<notifications@github.com&gt;; 
发送时间: 2020年5月7日(星期四) 晚上8:45
收件人: "MoePlayer/DPlayer"<DPlayer@noreply.github.com&gt;; 
抄送: "刘广宇"<xy14053156@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MoePlayer/DPlayer] 发现一个bug (#838)





 
我拿360试了也正常。
 
&mdash;

**Comment by kn007** [comment]
所述地址，无法复现

**Comment by xy14053156** [comment]
好的吧，你说的可以理解，但愿是我自己电脑的问题
