### ISSUE TITLE
能不能做一个画面拉伸功能，我实在是没找到

### ISSUE THREAD

**Issue by 1265578519** [MoePlayer/DPlayer#847]
有些片源比如说哆啦A梦，是16:9的影片，片源却是被拉伸成4:3的，想办法把他拉回去16:9

**Comment by Copay** [comment]
@1265578519 参考css属性 aspect-ratio
https://developer.mozilla.org/zh-CN/docs/Web/CSS/aspect-ratio

**Comment by 1265578519** [comment]
看了下没看懂，，，我放弃了
