### ISSUE TITLE
preload为auto时部分安卓手机hls播放视频加载失败

### ISSUE THREAD

**Issue by Amyas** [MoePlayer/DPlayer#860]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

部分安卓手机hls播放视频preload设置为auto时会视频加载失败

preload改为metadata后修复该问题

请问这是啥原理

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
https://github.com/video-dev/hls.js
