### ISSUE TITLE
"Segmented videos" do not works.

### ISSUE THREAD

**Issue by A-Circle-Zhang** [MoePlayer/DPlayer#93]
Only the first segment be played.
只会播放第一个分段。

- The steps to reproduce.
```
var dp = new DPlayer({
    // ...
    video: {
        url: ['1.mp4', '2.mp4', '3.mp4'],
        // ...
    }
});
```
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
[https://jsfiddle.net/2k6gh0m9/](https://jsfiddle.net/2k6gh0m9/)
- Which versions of DPlayer, and which browser / OS are affected by this issue?
DPlayer 1.3.2 / Chrome and Firefox

**Comment by DIYgod** [comment]
This feature is not supported any more.
