### ISSUE TITLE
After the control bar dragged, the screen (danmaku) should be cleaned.

### ISSUE THREAD

**Issue by A-Circle-Zhang** [MoePlayer/DPlayer#94]
进度条被拖动之后，弹幕应该被清屏。否则拖动之后屏幕会很混乱。
- The steps to reproduce.
**Play.**
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
**http://dplayer.js.org**
- Which versions of DPlayer, and which browser / OS are affected by this issue?
**Current Version.**

**Comment by DIYgod** [comment]
Done. 3d5ea2c68a9820d5923379a89bef629a635b6824
