### ISSUE TITLE
I can't pass（ anmaku.draw ）Draw the top or bottom bullet screen

### ISSUE THREAD

**Issue by jcdomt** [MoePlayer/DPlayer#947]
无论danmuku的type是right,top还是bottom，播放器都绘制right类型的弹幕

**Comment by LouisLuBrain** [comment]
在源码danmaku.js-draw()方法里有一个type的转换，这里是不是应该用临时变量啊?
要不然播放一次之后type全都变成字符串，number2Type全都返回‘right’。
（拙见笑纳）

**Comment by jcdomt** [comment]
懂了，直接在min.js的number2Type后面加return e;虽然很傻，但很管用(doge
