### ISSUE TITLE
When you switch the source, the binding event fails?What's the solution?

### ISSUE THREAD

**Issue by zhang134you** [MoePlayer/DPlayer#95]
When you switch the source, the binding event fails?What's the solution?

**Comment by dixyes** [comment]
趁你被作者吐槽之前 我来翻译下这个蜜汁模板：

如果要反馈问题，请提供以下信息：
If you want to report a bug, please provide the following information:

 - The steps to reproduce.
 - 复现步骤
 - A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
 - 如果可能的话，请在 https://jsfiddle.net 或 http://codepen.io/pen 提供一个最小化的demo
 - Which versions of DPlayer, and which browser / OS are affected by this issue?
 - 出现问题的DPlayer版本与系统/浏览器环境

**Comment by DIYgod** [comment]
@dixyes 问题说清楚，我能重现就行了...我种我应该不会吐槽的...

**Comment by zhang134you** [comment]
当我切换片源时，原来绑定的事件都失效了

**Comment by guokeke** [comment]
@zhang134you  事件绑在video上吗？ 在切换后重新绑定可行吗？

**Comment by DIYgod** [comment]
Fixed.
