### ISSUE TITLE
How do I set the request header

### ISSUE THREAD

**Issue by schizobulia** [MoePlayer/DPlayer#956]
The documentation doesn't say how to set it

**Comment by 1265578519** [comment]
同问题，能不能自定义一个头部，例如test: test
话说能不能去掉referer头

**Comment by schizobulia** [comment]
已经解决,DPlayer只是一个视频播放器，并不直接负责网络请求
可以参考以下代码：
```javascript
let request = new XMLHttpRequest();
request.responseType = 'blob';
request.open('get', 'map4 url', true);
request.setRequestHeader('Authorization', `123456`);
request.onreadystatechange = e => {
    if (request.readyState === XMLHttpRequest.DONE && request.status === 200) {
        const dp = new DPlayer({
            container: document.getElementById('dplayer'),
            video: {
                url: URL.createObjectURL(request.response),
            },
        });
    }
};
request.send(null);
```

**Comment by 1265578519** [comment]
感谢分享

**Comment by mayidadada** [comment]
> 已经解决,DPlayer只是一个视频播放器，并不直接负责网络请求
> 可以参考以下代码：
> 
> ```js
> let request = new XMLHttpRequest();
> request.responseType = 'blob';
> request.open('get', 'map4 url', true);
> request.setRequestHeader('Authorization', `123456`);
> request.onreadystatechange = e => {
>     if (request.readyState === XMLHttpRequest.DONE && request.status === 200) {
>         const dp = new DPlayer({
>             container: document.getElementById('dplayer'),
>             video: {
>                 url: URL.createObjectURL(request.response),
>             },
>         });
>     }
> };
> request.send(null);
> ```

请问这段代码应该添加到dplayer的哪个地方呢？

**Comment by 1265578519** [comment]
request.setRequestHeader('Authorization', `123456`);
js中吧，主要是这一段，添加一个header头部信息

**Comment by schizobulia** [comment]
> > 已经解决了，DPlayer只是一个视频播放器，不直接负责网络请求
> > 可以参考以下代码：
> > ```js
> > let  request  =  new  XMLHttpRequest ( ) ; 
> > 请求。responseType  =  'blob' ; 
> > 请求。open ( 'get' ,  'map4 url​​' ,  true ) ; 
> > 请求。setRequestHeader ( '授权' ,  '123456 ' ) ; 
> > 请求。onreadystatechange  =  e  =>  { 
> >     if  ( request . readyState  ===  XMLHttpRequest .完成 & 请求。状态 ===  200 ） { 
> >         const的 DP  = 新 DPlayer （{
> >             容器：文件。的getElementById （'dplayer' ），视频：{ URL：URL 。createObjectURL （请求。响应），} ，} ）; } } ; 请求。发送（空）
> >             
> >                 
> >             
> >         
> >     
> > 
> > ;
> > ```
> 
> 好像那个代码应该添加到dplayer的哪个地方呢？

setRequestHeader这里

**Comment by mayidadada** [comment]
> > > 已经解决了，DPlayer只是一个视频播放器，不直接负责网络请求
> > > 可以参考以下代码：
> > > ```js
> > > let   request   =   new   XMLHttpRequest  (  )  ; 
> > > 请求。responseType   =   'blob'  ; 
> > > 请求。open  (  'get'  ,   'map4 url​​ '  ,   true  )  ; 
> > > 请求。setRequestHeader  (  '授权'  ,   '123456 '  )  ; 
> > > 请求。onreadystatechange   =   e   =>   {  
> > >     if   (  request  .  readyState   ===   XMLHttpRequest  .完成 & 请求。状态 ===   200  )  {  
> > >         const的 DP   = 新 DPlayer  （{
> > >             容器：文件。的getElementById（'dplayer'  ），视频：{  URL：URL  .createObjectURL（请求。响应），}，}  ）;  }  }  ; 请求。发送（空）
> > >             
> > >                 
> > >             
> > >         
> > >     
> > > 
> > > ;
> > > ```
> > 
> > 
> > 好像那个代码应该添加到dplayer的哪个地方呢？
> 
> setRequestHeader这里

不好意思，我是不明白这段代码是添加到dplayer播放器里面的哪个文件里面！我对前端太陌生了！

**Comment by mayidadada** [comment]
> > > 已经解决了，DPlayer只是一个视频播放器，不直接负责网络请求
> > > 可以参考以下代码：
> > > ```js
> > > let   request   =   new   XMLHttpRequest  (  )  ; 
> > > 请求。responseType   =   'blob'  ; 
> > > 请求。open  (  'get'  ,   'map4 url​​ '  ,   true  )  ; 
> > > 请求。setRequestHeader  (  '授权'  ,   '123456 '  )  ; 
> > > 请求。onreadystatechange   =   e   =>   {  
> > >     if   (  request  .  readyState   ===   XMLHttpRequest  .完成 & 请求。状态 ===   200  )  {  
> > >         const的 DP   = 新 DPlayer  （{
> > >             容器：文件。的getElementById（'dplayer'  ），视频：{  URL：URL  .createObjectURL（请求。响应），}，}  ）;  }  }  ; 请求。发送（空）
> > >             
> > >                 
> > >             
> > >         
> > >     
> > > 
> > > ;
> > > ```
> > 
> > 
> > 好像那个代码应该添加到dplayer的哪个地方呢？
> 
> setRequestHeader这里

请大佬指点一下！

**Comment by 1265578519** [comment]
不是加到播放器，是加到前端
