### ISSUE TITLE
npm run dev has error

### ISSUE THREAD

**Issue by fuerpeng** [MoePlayer/DPlayer#96]
![image](https://user-images.githubusercontent.com/24818415/27533363-de361af2-5a95-11e7-8cc9-cfcaedaad1d6.png)

npm ERR! dplayer@1.4.1 dev: `WEBPACK_ENV=dev webpack-dev-server --hot --progress
 --inline --host 0.0.0.0`

**Comment by dixyes** [comment]
“ENV_VAR=sth exec some command” is some bash style command , cmd won't understand
you may try setting ENV_VAR before execute command
like
    WEBPACK_ENV=dev
    webpack-dev-server --hot --progress --inline --host 0.0.0.0
(I don't know where to find webpack-dev-server, hope it's in your PATH or can be easily found in node installed dir

**Comment by micooz** [comment]
@DIYgod Suggestion: [cross-env](https://github.com/kentcdodds/cross-env) is a good approach to handle environment variables on different platforms.
